# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: nvsentinel-gpu-health-monitor
  namespace: {{ .Release.Namespace }}
data:
  config.ini: |
    [logging]
    LogFormat = %%(asctime)s,%%(msecs)03d %%(levelname)-8s [%%(filename)s:%%(lineno)d] %%(message)s
    DateTimeFormat = %%Y-%%m-%%d:%%H:%%M:%%S

    [dcgm]
    PollIntervalSeconds = 15

    [eventprocessors.kubernetes]
    ConflictRetryCount = 10
    FatalXidErrors = 63,64,93

    [eventprocessors.platformconnector]
    SocketPath = /var/run/nvsentinel.sock

    [cli]
    EnabledEventProcessors = PlatformConnectorEventProcessor
    
    [xiderrorsconfig]
    XidErrorsBatchProcessingEnabled = false
    XidErrorsSlidingWindowSize = 3
    XidErrorsBatchProcessingInterval = 10

    [xiderrorrecommendactiontoplatformconnectormapping]
    UNEXPECTED_ERR_REPORT_ISSUE = 5
    WORKFLOW_XID_13_31 = 7
    IGNORE = 0
    WORKFLOW_ECC_DBE_SRAM = 8
    REPORT_ISSUE = 5
    RUN_FIELDDIAG = 6
    RESTART_APP = 4
    RESET_GPU = 2
    RESOLUTION_BUCKET_TBD = 99
    WORKFLOW_NVLINK5_ERR = 9
    WORKFLOW_XID_45 = 10
    WORKFLOW_XID_48 = 11
    CHECK_MECHANICALS = 12
    WORKFLOW_NVLINK_ERR = 13
    UPDATE_SWFW = 14
    RESTART_VM = 15

  # The below tables should map to the xid error spreadsheet https://docs.google.com/spreadsheets/d/1t6PpsC5TXiNl4JMBuHlFIjmSbjLZ2ik0Sz3DLw8cLmE/edit?gid=121017179#gid=121017179
  #ordering of below columns => xiderrorno,xiderrorname,xiderrorrecommendedaction,FATAL/NONFATAL errors
  xiderrorsmapping.csv: |
    1,ROBUST_CHANNEL_FIFO_ERROR_FIFO_METHOD,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    2,ROBUST_CHANNEL_FIFO_ERROR_SW_METHOD,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    3,ROBUST_CHANNEL_FIFO_ERROR_UNK_METHOD,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    4,ROBUST_CHANNEL_FIFO_ERROR_CHANNEL_BUSY,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    5,ROBUST_CHANNEL_FIFO_ERROR_RUNOUT_OVERFLOW,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    6,ROBUST_CHANNEL_FIFO_ERROR_PARSE_ERR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    7,ROBUST_CHANNEL_FIFO_ERROR_PTE_ERR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    8,ROBUST_CHANNEL_FIFO_ERROR_IDLE_TIMEOUT,UNEXPECTED_ERR_REPORT_ISSUE,NONFATAL
    9,ROBUST_CHANNEL_GR_ERROR_INSTANCE,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    10,ROBUST_CHANNEL_GR_ERROR_SINGLE_STEP,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    11,ROBUST_CHANNEL_GR_ERROR_MISSING_HW,UNEXPECTED_ERR_REPORT_ISSUE,NONFATAL
    12,ROBUST_CHANNEL_GR_ERROR_SW_METHOD,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    13,ROBUST_CHANNEL_GR_ERROR_SW_NOTIFY,RESTART_APP,NONFATAL
    14,ROBUST_CHANNEL_FAKE_ERROR,IGNORE,NONFATAL
    15,ROBUST_CHANNEL_SCANLINE_TIMEOUT,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    16,ROBUST_CHANNEL_FAKE_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    17,ROBUST_CHANNEL_PARAMETER_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    18,ROBUST_CHANNEL_BUS_MASTER_TIMEOUT_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    19,ROBUST_CHANNEL_DISP_MISSED_NOTIFIER,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    20,ROBUST_CHANNEL_MPEG_ERROR_SW_METHOD,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    21,ROBUST_CHANNEL_ME_ERROR_SW_METHOD,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    22,ROBUST_CHANNEL_VP_ERROR_SW_METHOD,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    23,ROBUST_CHANNEL_RC_LOGGING_ENABLED,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    24,ROBUST_CHANNEL_GR_SEMAPHORE_TIMEOUT,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    25,ROBUST_CHANNEL_GR_ILLEGAL_NOTIFY,UNEXPECTED_ERR_REPORT_ISSUE,NONFATAL
    26,ROBUST_CHANNEL_FIFO_ERROR_FBISTATE_TIMEOUT,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    27,ROBUST_CHANNEL_VP_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    28,ROBUST_CHANNEL_VP2_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    29,ROBUST_CHANNEL_BSP_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    30,ROBUST_CHANNEL_BAD_ADDR_ACCESS,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    31,ROBUST_CHANNEL_FIFO_ERROR_MMU_ERR_FLT,RESTART_APP,NONFATAL
    32,ROBUST_CHANNEL_PBDMA_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,NONFATAL
    33,ROBUST_CHANNEL_SEC_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    34,ROBUST_CHANNEL_MSVLD_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    35,ROBUST_CHANNEL_MSPDEC_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    36,ROBUST_CHANNEL_MSPPP_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    37,ROBUST_CHANNEL_FECS_ERR_UNIMP_FIRMWARE_METHOD,IGNORE,NONFATAL
    38,ROBUST_CHANNEL_FECS_ERR_WATCHDOG_TIMEOUT,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    39,ROBUST_CHANNEL_CE0_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,NONFATAL
    40,ROBUST_CHANNEL_CE1_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,NONFATAL
    41,ROBUST_CHANNEL_CE2_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,NONFATAL
    42,ROBUST_CHANNEL_VIC_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,NONFATAL
    43,ROBUST_CHANNEL_RESETCHANNEL_VERIF_ERROR,IGNORE,NONFATAL
    44,ROBUST_CHANNEL_GR_FAULT_DURING_CTXSW,UNEXPECTED_ERR_REPORT_ISSUE,NONFATAL
    45,ROBUST_CHANNEL_PREEMPTIVE_REMOVAL,WORKFLOW_XID_45,NONFATAL
    46,ROBUST_CHANNEL_GPU_TIMEOUT_ERROR,RESET_GPU,FATAL
    47,ROBUST_CHANNEL_NVENC0_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    48,ROBUST_CHANNEL_GPU_ECC_DBE,WORKFLOW_XID_48,FATAL
    49,SILENT_RUNNING_CONSTANT_LEVEL_SET_BY_REGISTRY,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    50,SILENT_RUNNING_LEVEL_TRANSITION_DUE_TO_RC_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    51,SILENT_RUNNING_STRESS_TEST_FAILURE,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    52,SILENT_RUNNING_LEVEL_TRANS_DUE_TO_TEMP_RISE,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    53,SILENT_RUNNING_TEMP_REDUCED_CLOCKING,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    54,SILENT_RUNNING_PWR_REDUCED_CLOCKING,CHECK_MECHANICALS,FATAL
    55,SILENT_RUNNING_TEMPERATURE_READ_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    56,DISPLAY_CHANNEL_EXCEPTION,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    57,FB_LINK_TRAINING_FAILURE_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    58,FB_MEMORY_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    59,PMU_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    60,ROBUST_CHANNEL_SEC2_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,NONFATAL
    61,PMU_BREAKPOINT,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    62,PMU_HALT_ERROR,RESET_GPU,FATAL
    63,INFOROM_DRAM_RETIREMENT_EVENT,IGNORE,NONFATAL
    64,INFOROM_DRAM_RETIREMENT_FAILURE,RESET_GPU,FATAL
    65,ROBUST_CHANNEL_NVENC1_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    66,ROBUST_CHANNEL_FECS_ERR_REG_ACCESS_VIOLATION,UNEXPECTED_ERR_REPORT_ISSUE,NONFATAL
    67,ROBUST_CHANNEL_FECS_ERR_VERIF_VIOLATION,UNEXPECTED_ERR_REPORT_ISSUE,NONFATAL
    68,ROBUST_CHANNEL_NVDEC0_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,NONFATAL
    69,ROBUST_CHANNEL_GR_CLASS_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,NONFATAL
    70,ROBUST_CHANNEL_CE3_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,NONFATAL
    71,ROBUST_CHANNEL_CE4_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,NONFATAL
    72,ROBUST_CHANNEL_CE5_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,NONFATAL
    73,ROBUST_CHANNEL_NVENC2_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    74,NVLINK_ERROR,WORKFLOW_NVLINK_ERR,WORKFLOW_NVLINK_ERR,FATAL
    75,ROBUST_CHANNEL_CE6_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,RESTART_APP,NONFATAL
    76,ROBUST_CHANNEL_CE7_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,RESTART_APP,NONFATAL
    77,ROBUST_CHANNEL_CE8_ERROR,ROBUST_CHANNEL_CE8_ERROR,RESTART_APP,NONFATAL
    78,VGPU_START_ERROR,UPDATE_SWFW,FATAL
    79,ROBUST_CHANNEL_GPU_HAS_FALLEN_OFF_THE_BUS,RUN_FIELDDIAG,FATAL
    80,PBDMA_PUSHBUFFER_CRC_MISMATCH,RESTART_APP,NONFATAL
    81,ROBUST_CHANNEL_VGA_SUBSYSTEM_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    82,ROBUST_CHANNEL_NVJPG0_ERROR,RESTART_APP,NONFATAL
    83,ROBUST_CHANNEL_NVDEC1_ERROR,RESTART_APP,NONFATAL
    84,ROBUST_CHANNEL_NVDEC2_ERROR,RESTART_APP,NONFATAL
    85,ROBUST_CHANNEL_CE9_ERROR,RESTART_APP,NONFATAL
    86,ROBUST_CHANNEL_OFA0_ERROR,RESTART_APP,NONFATAL
    87,NVTELEMETRY_DRIVER_REPORT,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    88,ROBUST_CHANNEL_NVDEC3_ERROR,RESTART_APP,NONFATAL
    89,ROBUST_CHANNEL_NVDEC4_ERROR,RESTART_APP,NONFATAL
    90,LTC_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    91,RESERVED_XID,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    92,EXCESSIVE_SBE_INTERRUPTS,RUN_FIELDDIAG,FATAL
    93,INFOROM_ERASE_LIMIT_EXCEEDED,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    94,ROBUST_CHANNEL_CONTAINED_ERROR,RESTART_APP,NONFATAL
    95,ROBUST_CHANNEL_UNCONTAINED_ERROR,RESET_GPU,FATAL
    96,ROBUST_CHANNEL_NVDEC5_ERROR,RESTART_APP,NONFATAL
    97,ROBUST_CHANNEL_NVDEC6_ERROR,RESTART_APP,NONFATAL
    98,ROBUST_CHANNEL_NVDEC7_ERROR,RESTART_APP,NONFATAL
    99,ROBUST_CHANNEL_NVJPG1_ERROR,RESTART_APP,NONFATAL
    100,ROBUST_CHANNEL_NVJPG2_ERROR,RESTART_APP,NONFATAL
    101,ROBUST_CHANNEL_NVJPG3_ERROR,RESTART_APP,NONFATAL
    102,ROBUST_CHANNEL_NVJPG4_ERROR,RESTART_APP,NONFATAL
    103,ROBUST_CHANNEL_NVJPG5_ERROR,RESTART_APP,NONFATAL
    104,ROBUST_CHANNEL_NVJPG6_ERROR,RESTART_APP,NONFATAL
    105,ROBUST_CHANNEL_NVJPG7_ERROR,RESTART_APP,NONFATAL
    106,SMBPBI_TEST_MESSAGE,IGNORE,NONFATAL
    107,SMBPBI_TEST_MESSAGE_SILENT,IGNORE,NONFATAL
    108,DESTINATION_FLA_TRANSLATION_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    109,ROBUST_CHANNEL_CTXSW_TIMEOUT_ERROR,REPORT_ISSUE,NONFATAL
    110,SEC_FAULT_ERROR,RESET_GPU,FATAL
    111,BUNDLE_ERROR_EVENT,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    112,DISP_SUPERVISOR_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    113,DP_LT_FAILURE,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    114,HEAD_RG_UNDERFLOW,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    115,CORE_CHANNEL_REGS,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    116,WINDOW_CHANNEL_REGS,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    117,CURSOR_CHANNEL_REGS,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    118,HEAD_REGS,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    119,GSP_RPC_TIMEOUT,RESET_GPU,FATAL
    120,GSP_ERROR,RESET_GPU,FATAL
    121,C2C_ERROR,IGNORE,NONFATAL
    122,SPI_PMU_RPC_READ_FAIL,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    123,SPI_PMU_RPC_READ_FAIL,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    124,SPI_PMU_RPC_WRITE_FAIL,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    125,INFOROM_FS_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    126,ROBUST_CHANNEL_CE10_ERROR,RESTART_APP,NONFATAL
    127,ROBUST_CHANNEL_CE11_ERROR,RESTART_APP,NONFATAL
    128,ROBUST_CHANNEL_CE12_ERROR,RESTART_APP,NONFATAL
    129,ROBUST_CHANNEL_CE13_ERROR,RESTART_APP,NONFATAL
    130,ROBUST_CHANNEL_CE14_ERROR,RESTART_APP,NONFATAL
    131,ROBUST_CHANNEL_CE15_ERROR,RESTART_APP,NONFATAL
    132,ROBUST_CHANNEL_CE16_ERROR,RESTART_APP,NONFATAL
    133,ROBUST_CHANNEL_CE17_ERROR,RESTART_APP,NONFATAL
    134,ROBUST_CHANNEL_CE18_ERROR,RESTART_APP,NONFATAL
    135,ROBUST_CHANNEL_CE19_ERROR,RESTART_APP,NONFATAL
    136,ALI_TRAINING_FAIL,RESET_GPU,FATAL
    137,NVLINK_FLA_PRIV_ERR,IGNORE,NONFATAL
    138,ROBUST_CHANNEL_DLA_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    139,ROBUST_CHANNEL_OFA1_ERROR,RESTART_APP,NONFATAL
    140,UNRECOVERABLE_ECC_ERROR_ESCAPE,RESET_GPU,FATAL
    141,ROBUST_CHANNEL_FAST_PATH_ERROR,IGNORE,NONFATAL
    142,ROBUST_CHANNEL_NVENC3_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    143,GPU_INIT_ERROR,RUN_FIELDDIAG,FATAL
    144,NVLINK_SAW_ERROR,WORKFLOW_NVLINK5_ERR,FATAL
    145,NVLINK_RLW_ERROR,WORKFLOW_NVLINK5_ERR,FATAL
    146,NVLINK_TLW_ERROR,WORKFLOW_NVLINK5_ERR,FATAL
    147,NVLINK_TREX_ERROR,WORKFLOW_NVLINK5_ERR,FATAL
    148,NVLINK_NVLPW_CTRL_ERROR,WORKFLOW_NVLINK5_ERR,FATAL
    149,NVLINK_NETIR_ERROR,WORKFLOW_NVLINK5_ERR,FATAL
    150,NVLINK_MSE_ERROR,WORKFLOW_NVLINK5_ERR,FATAL
    151,ROBUST_CHANNEL_KEY_ROTATION_ERROR,RESTART_VM,FATAL
    152,ROBUST_CHANNEL_DLA_SMMU_ERROR,IGNORE,NONFATAL
    153,ROBUST_CHANNEL_DLA_TIMEOUT,IGNORE,NONFATAL
    154,GPU_RECOVERY_ACTION_CHANGED,RESOLUTION_BUCKET_TBD,NONFATAL
    155,NVLINK_SW_DEFINED_ERROR,RESET_GPU,FATAL
    156,RESOURCE_RETIREMENT_EVENT,RESET_GPU,FATAL
    157,RESOURCE_RETIREMENT_FAILURE,IGNORE,NONFATAL
    158,GPU_FATAL_TIMEOUT,RESET_GPU,FATAL,
    159,ROBUST_CHANNEL_CHI_NON_DATA_ERROR,IGNORE,NONFATAL
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: nvsentinel
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-connector-configmap
data:
  config.json: |
    {
      "enableK8sPlatformConnector": "false",
      "enableNodeHealthEventsUDSConnector": "true"
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: nvsentinel-node-health-events-uds-connector
  namespace: {{ .Release.Namespace }}
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchFields:
              - key: metadata.name
                operator: In
                values:
                  - minikube
  containers:
  - name: nvsentinel-node-health-events-uds-connector
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    image: nvcr.io/nv-ngc-devops/nvsentinel-node-health-events-uds-connector-server:main
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 2112
      name: metrics
      protocol: TCP
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi
    securityContext:
      privileged: true
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run
      name: var-run-vol
    - mountPath: /etc/config/
      name: platform-connector-configmap
    - mountPath: /etc/dcgmhealth
      name: config-vol
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: nvidia-ngcuser-pull-secret
  restartPolicy: Always
  securityContext: {}
  serviceAccount: nvsentinel
  serviceAccountName: nvsentinel
  terminationGracePeriodSeconds: 30
  tolerations:
    - operator: Exists
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/disk-pressure
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/memory-pressure
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/pid-pressure
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/unschedulable
      operator: Exists
  volumes:
    - hostPath:
        path: /var/run/nvsentinel
        type: DirectoryOrCreate
      name: var-run-vol
    - configMap:
        defaultMode: 420
        name: platform-connector-configmap
      name: platform-connector-configmap
    - configMap:
        defaultMode: 420
        name: nvsentinel-gpu-health-monitor
      name: config-vol