[supervisord]
nodaemon=true

[program:platform-connector]
command=/app/platform-connector --metrics-port=2112 -socket=/var/run/nvsentinel.sock -nodehealtheventssocket=/var/run/nodeHealthEvents.sock
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autostart=true
autorestart=true

[program:gpu_health_monitor]
command=gpu_health_monitor --config-file=/etc/dcgmhealth/config.ini --xid-error-mapping-config-file=/etc/dcgmhealth/xiderrorsmapping.csv --dcgm-addr=localhost:5555 --port="8000" --verbose="True" --state-file=/var/run/statefile --dcgm-k8s-service-enabled="true"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autostart=true
autorestart=true