// Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.1
// source: platformconnector.proto

package platform_connectors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecommenedAction int32

const (
	RecommenedAction_NONE                                 RecommenedAction = 0
	RecommenedAction_NODE_REBOOT                          RecommenedAction = 1
	RecommenedAction_COMPONENT_RESET                      RecommenedAction = 2
	RecommenedAction_COMPONENT_REPLACEMENT                RecommenedAction = 3
	RecommenedAction_APPLICATION_RESTART                  RecommenedAction = 4
	RecommenedAction_REPORT_ISSUE                         RecommenedAction = 5
	RecommenedAction_RUN_FIELDDIAG                        RecommenedAction = 6
	RecommenedAction_WORKFLOW_XID_13_31                   RecommenedAction = 7
	RecommenedAction_WORKFLOW_ECC_DBE_SRAM                RecommenedAction = 8
	RecommenedAction_WORKFLOW_NVLINK5_ERR                 RecommenedAction = 9
	RecommenedAction_WORKFLOW_XID_45                      RecommenedAction = 10
	RecommenedAction_WORKFLOW_XID_48                      RecommenedAction = 11
	RecommenedAction_CHECK_MECHANICALS                    RecommenedAction = 12
	RecommenedAction_WORKFLOW_NVLINK_ERR                  RecommenedAction = 13
	RecommenedAction_UPDATE_SWFW                          RecommenedAction = 14
	RecommenedAction_RESTART_VM                           RecommenedAction = 15
	RecommenedAction_RESET_FABRIC                         RecommenedAction = 16
	RecommenedAction_WORKFLOW_NVLINK_POTENTIALY_FATAL_ERR RecommenedAction = 17
	RecommenedAction_CHECK_FM_CONFIG                      RecommenedAction = 18
	RecommenedAction_CHECK_THERMALS                       RecommenedAction = 19
	RecommenedAction_RESET_GPU                            RecommenedAction = 20
	RecommenedAction_CHECK_LINK_MECHANICAL_CONNECTIONS    RecommenedAction = 21
	RecommenedAction_INVESTIGATE_LINK_SI                  RecommenedAction = 22
	RecommenedAction_CHECK_UVM                            RecommenedAction = 23
	RecommenedAction_RESTART_BM                           RecommenedAction = 24
	RecommenedAction_UNKNOWN                              RecommenedAction = 99
)

// Enum value maps for RecommenedAction.
var (
	RecommenedAction_name = map[int32]string{
		0:  "NONE",
		1:  "NODE_REBOOT",
		2:  "COMPONENT_RESET",
		3:  "COMPONENT_REPLACEMENT",
		4:  "APPLICATION_RESTART",
		5:  "REPORT_ISSUE",
		6:  "RUN_FIELDDIAG",
		7:  "WORKFLOW_XID_13_31",
		8:  "WORKFLOW_ECC_DBE_SRAM",
		9:  "WORKFLOW_NVLINK5_ERR",
		10: "WORKFLOW_XID_45",
		11: "WORKFLOW_XID_48",
		12: "CHECK_MECHANICALS",
		13: "WORKFLOW_NVLINK_ERR",
		14: "UPDATE_SWFW",
		15: "RESTART_VM",
		16: "RESET_FABRIC",
		17: "WORKFLOW_NVLINK_POTENTIALY_FATAL_ERR",
		18: "CHECK_FM_CONFIG",
		19: "CHECK_THERMALS",
		20: "RESET_GPU",
		21: "CHECK_LINK_MECHANICAL_CONNECTIONS",
		22: "INVESTIGATE_LINK_SI",
		23: "CHECK_UVM",
		24: "RESTART_BM",
		99: "UNKNOWN",
	}
	RecommenedAction_value = map[string]int32{
		"NONE":                                 0,
		"NODE_REBOOT":                          1,
		"COMPONENT_RESET":                      2,
		"COMPONENT_REPLACEMENT":                3,
		"APPLICATION_RESTART":                  4,
		"REPORT_ISSUE":                         5,
		"RUN_FIELDDIAG":                        6,
		"WORKFLOW_XID_13_31":                   7,
		"WORKFLOW_ECC_DBE_SRAM":                8,
		"WORKFLOW_NVLINK5_ERR":                 9,
		"WORKFLOW_XID_45":                      10,
		"WORKFLOW_XID_48":                      11,
		"CHECK_MECHANICALS":                    12,
		"WORKFLOW_NVLINK_ERR":                  13,
		"UPDATE_SWFW":                          14,
		"RESTART_VM":                           15,
		"RESET_FABRIC":                         16,
		"WORKFLOW_NVLINK_POTENTIALY_FATAL_ERR": 17,
		"CHECK_FM_CONFIG":                      18,
		"CHECK_THERMALS":                       19,
		"RESET_GPU":                            20,
		"CHECK_LINK_MECHANICAL_CONNECTIONS":    21,
		"INVESTIGATE_LINK_SI":                  22,
		"CHECK_UVM":                            23,
		"RESTART_BM":                           24,
		"UNKNOWN":                              99,
	}
)

func (x RecommenedAction) Enum() *RecommenedAction {
	p := new(RecommenedAction)
	*p = x
	return p
}

func (x RecommenedAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecommenedAction) Descriptor() protoreflect.EnumDescriptor {
	return file_platformconnector_proto_enumTypes[0].Descriptor()
}

func (RecommenedAction) Type() protoreflect.EnumType {
	return &file_platformconnector_proto_enumTypes[0]
}

func (x RecommenedAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecommenedAction.Descriptor instead.
func (RecommenedAction) EnumDescriptor() ([]byte, []int) {
	return file_platformconnector_proto_rawDescGZIP(), []int{0}
}

type HealthEvents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Events        []*HealthEvent         `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthEvents) Reset() {
	*x = HealthEvents{}
	mi := &file_platformconnector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthEvents) ProtoMessage() {}

func (x *HealthEvents) ProtoReflect() protoreflect.Message {
	mi := &file_platformconnector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthEvents.ProtoReflect.Descriptor instead.
func (*HealthEvents) Descriptor() ([]byte, []int) {
	return file_platformconnector_proto_rawDescGZIP(), []int{0}
}

func (x *HealthEvents) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *HealthEvents) GetEvents() []*HealthEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entityType,proto3" json:"entityType,omitempty"`
	EntityValue   string                 `protobuf:"bytes,2,opt,name=entityValue,proto3" json:"entityValue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_platformconnector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_platformconnector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_platformconnector_proto_rawDescGZIP(), []int{1}
}

func (x *Entity) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *Entity) GetEntityValue() string {
	if x != nil {
		return x.EntityValue
	}
	return ""
}

type HealthEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Version            uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Agent              string                 `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	ComponentClass     string                 `protobuf:"bytes,3,opt,name=componentClass,proto3" json:"componentClass,omitempty"`
	CheckName          string                 `protobuf:"bytes,4,opt,name=checkName,proto3" json:"checkName,omitempty"`
	IsFatal            bool                   `protobuf:"varint,5,opt,name=isFatal,proto3" json:"isFatal,omitempty"`
	IsHealthy          bool                   `protobuf:"varint,6,opt,name=isHealthy,proto3" json:"isHealthy,omitempty"`
	Message            string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	RecommendedAction  RecommenedAction       `protobuf:"varint,8,opt,name=recommendedAction,proto3,enum=platformconnector.RecommenedAction" json:"recommendedAction,omitempty"`
	ErrorCode          []string               `protobuf:"bytes,9,rep,name=errorCode,proto3" json:"errorCode,omitempty"`
	EntitiesImpacted   []*Entity              `protobuf:"bytes,10,rep,name=entitiesImpacted,proto3" json:"entitiesImpacted,omitempty"`
	Metadata           map[string]string      `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	GeneratedTimestamp *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=generatedTimestamp,proto3" json:"generatedTimestamp,omitempty"`
	NodeName           string                 `protobuf:"bytes,13,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HealthEvent) Reset() {
	*x = HealthEvent{}
	mi := &file_platformconnector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthEvent) ProtoMessage() {}

func (x *HealthEvent) ProtoReflect() protoreflect.Message {
	mi := &file_platformconnector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthEvent.ProtoReflect.Descriptor instead.
func (*HealthEvent) Descriptor() ([]byte, []int) {
	return file_platformconnector_proto_rawDescGZIP(), []int{2}
}

func (x *HealthEvent) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *HealthEvent) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *HealthEvent) GetComponentClass() string {
	if x != nil {
		return x.ComponentClass
	}
	return ""
}

func (x *HealthEvent) GetCheckName() string {
	if x != nil {
		return x.CheckName
	}
	return ""
}

func (x *HealthEvent) GetIsFatal() bool {
	if x != nil {
		return x.IsFatal
	}
	return false
}

func (x *HealthEvent) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

func (x *HealthEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthEvent) GetRecommendedAction() RecommenedAction {
	if x != nil {
		return x.RecommendedAction
	}
	return RecommenedAction_NONE
}

func (x *HealthEvent) GetErrorCode() []string {
	if x != nil {
		return x.ErrorCode
	}
	return nil
}

func (x *HealthEvent) GetEntitiesImpacted() []*Entity {
	if x != nil {
		return x.EntitiesImpacted
	}
	return nil
}

func (x *HealthEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *HealthEvent) GetGeneratedTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedTimestamp
	}
	return nil
}

func (x *HealthEvent) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

var File_platformconnector_proto protoreflect.FileDescriptor

const file_platformconnector_proto_rawDesc = "" +
	"\n" +
	"\x17platformconnector.proto\x12\x11platformconnector\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"`\n" +
	"\fHealthEvents\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x126\n" +
	"\x06events\x18\x02 \x03(\v2\x1e.platformconnector.HealthEventR\x06events\"J\n" +
	"\x06Entity\x12\x1e\n" +
	"\n" +
	"entityType\x18\x01 \x01(\tR\n" +
	"entityType\x12 \n" +
	"\ventityValue\x18\x02 \x01(\tR\ventityValue\"\xfc\x04\n" +
	"\vHealthEvent\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x14\n" +
	"\x05agent\x18\x02 \x01(\tR\x05agent\x12&\n" +
	"\x0ecomponentClass\x18\x03 \x01(\tR\x0ecomponentClass\x12\x1c\n" +
	"\tcheckName\x18\x04 \x01(\tR\tcheckName\x12\x18\n" +
	"\aisFatal\x18\x05 \x01(\bR\aisFatal\x12\x1c\n" +
	"\tisHealthy\x18\x06 \x01(\bR\tisHealthy\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12Q\n" +
	"\x11recommendedAction\x18\b \x01(\x0e2#.platformconnector.RecommenedActionR\x11recommendedAction\x12\x1c\n" +
	"\terrorCode\x18\t \x03(\tR\terrorCode\x12E\n" +
	"\x10entitiesImpacted\x18\n" +
	" \x03(\v2\x19.platformconnector.EntityR\x10entitiesImpacted\x12H\n" +
	"\bmetadata\x18\v \x03(\v2,.platformconnector.HealthEvent.MetadataEntryR\bmetadata\x12J\n" +
	"\x12generatedTimestamp\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x12generatedTimestamp\x12\x1a\n" +
	"\bnodeName\x18\r \x01(\tR\bnodeName\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xc3\x04\n" +
	"\x10RecommenedAction\x12\b\n" +
	"\x04NONE\x10\x00\x12\x0f\n" +
	"\vNODE_REBOOT\x10\x01\x12\x13\n" +
	"\x0fCOMPONENT_RESET\x10\x02\x12\x19\n" +
	"\x15COMPONENT_REPLACEMENT\x10\x03\x12\x17\n" +
	"\x13APPLICATION_RESTART\x10\x04\x12\x10\n" +
	"\fREPORT_ISSUE\x10\x05\x12\x11\n" +
	"\rRUN_FIELDDIAG\x10\x06\x12\x16\n" +
	"\x12WORKFLOW_XID_13_31\x10\a\x12\x19\n" +
	"\x15WORKFLOW_ECC_DBE_SRAM\x10\b\x12\x18\n" +
	"\x14WORKFLOW_NVLINK5_ERR\x10\t\x12\x13\n" +
	"\x0fWORKFLOW_XID_45\x10\n" +
	"\x12\x13\n" +
	"\x0fWORKFLOW_XID_48\x10\v\x12\x15\n" +
	"\x11CHECK_MECHANICALS\x10\f\x12\x17\n" +
	"\x13WORKFLOW_NVLINK_ERR\x10\r\x12\x0f\n" +
	"\vUPDATE_SWFW\x10\x0e\x12\x0e\n" +
	"\n" +
	"RESTART_VM\x10\x0f\x12\x10\n" +
	"\fRESET_FABRIC\x10\x10\x12(\n" +
	"$WORKFLOW_NVLINK_POTENTIALY_FATAL_ERR\x10\x11\x12\x13\n" +
	"\x0fCHECK_FM_CONFIG\x10\x12\x12\x12\n" +
	"\x0eCHECK_THERMALS\x10\x13\x12\r\n" +
	"\tRESET_GPU\x10\x14\x12%\n" +
	"!CHECK_LINK_MECHANICAL_CONNECTIONS\x10\x15\x12\x17\n" +
	"\x13INVESTIGATE_LINK_SI\x10\x16\x12\r\n" +
	"\tCHECK_UVM\x10\x17\x12\x0e\n" +
	"\n" +
	"RESTART_BM\x10\x18\x12\v\n" +
	"\aUNKNOWN\x10c2f\n" +
	"\x11PlatformConnector\x12Q\n" +
	"\x14HealthEventOccuredV1\x12\x1f.platformconnector.HealthEvents\x1a\x16.google.protobuf.Empty\"\x00BRZPgitlab-master.nvidia.com/dgxcloud/mk8s/k8s-addons/nvsentinel/platform-connectorsb\x06proto3"

var (
	file_platformconnector_proto_rawDescOnce sync.Once
	file_platformconnector_proto_rawDescData []byte
)

func file_platformconnector_proto_rawDescGZIP() []byte {
	file_platformconnector_proto_rawDescOnce.Do(func() {
		file_platformconnector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platformconnector_proto_rawDesc), len(file_platformconnector_proto_rawDesc)))
	})
	return file_platformconnector_proto_rawDescData
}

var file_platformconnector_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_platformconnector_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_platformconnector_proto_goTypes = []any{
	(RecommenedAction)(0),         // 0: platformconnector.RecommenedAction
	(*HealthEvents)(nil),          // 1: platformconnector.HealthEvents
	(*Entity)(nil),                // 2: platformconnector.Entity
	(*HealthEvent)(nil),           // 3: platformconnector.HealthEvent
	nil,                           // 4: platformconnector.HealthEvent.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
}
var file_platformconnector_proto_depIdxs = []int32{
	3, // 0: platformconnector.HealthEvents.events:type_name -> platformconnector.HealthEvent
	0, // 1: platformconnector.HealthEvent.recommendedAction:type_name -> platformconnector.RecommenedAction
	2, // 2: platformconnector.HealthEvent.entitiesImpacted:type_name -> platformconnector.Entity
	4, // 3: platformconnector.HealthEvent.metadata:type_name -> platformconnector.HealthEvent.MetadataEntry
	5, // 4: platformconnector.HealthEvent.generatedTimestamp:type_name -> google.protobuf.Timestamp
	1, // 5: platformconnector.PlatformConnector.HealthEventOccuredV1:input_type -> platformconnector.HealthEvents
	6, // 6: platformconnector.PlatformConnector.HealthEventOccuredV1:output_type -> google.protobuf.Empty
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_platformconnector_proto_init() }
func file_platformconnector_proto_init() {
	if File_platformconnector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platformconnector_proto_rawDesc), len(file_platformconnector_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_platformconnector_proto_goTypes,
		DependencyIndexes: file_platformconnector_proto_depIdxs,
		EnumInfos:         file_platformconnector_proto_enumTypes,
		MessageInfos:      file_platformconnector_proto_msgTypes,
	}.Build()
	File_platformconnector_proto = out.File
	file_platformconnector_proto_goTypes = nil
	file_platformconnector_proto_depIdxs = nil
}
