variables:
  GIT_TERMINAL_PROMPT: 1
  NGC_ORG: nv-ngc-devops
  NGC_USER_NAME: '$$oauthtoken'
  NVCR_CONTAINER_REPO: nvcr.io
  HELM_URL: https://helm.ngc.nvidia.com

  KANIKO_IMAGE: "gcr.io/kaniko-project/executor:v1.19.2-debug"

  # When using dind service, you must instruct docker to talk with the
  # daemon started inside of the service. The daemon is available with
  # a network connection instead of the default /var/run/docker.sock socket.
  #
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services
  #
  # If you're using GitLab Runner 12.7 or earlier with the Kubernetes executor and Kubernetes 1.6 or earlier,
  # the variable must be set to tcp://localhost:2375 because of how the
  # Kubernetes executor connects services to the job container
  # DOCKER_HOST: tcp://localhost:2375
  #
  DOCKER_HOST: tcp://docker:2375
  #
  # This instructs Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""

image: $CI_REGISTRY_IMAGE/ci:latest

stages:
  - lint
  - test
  - publish
  - deploy

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

protos lint:
  stage: lint
  script:
    - protoc -I protobufs/ --go_out=platform-connectors/pkg/protos/ --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative --go-grpc_out=platform-connectors/pkg/protos/ protobufs/platformconnector.proto
    - protoc -I protobufs/ --go_out=health-monitors/nic-health-monitor/pkg/protos/ --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative --go-grpc_out=health-monitors/nic-health-monitor/pkg/protos/ protobufs/platformconnector.proto
    - protoc -I protobufs/ --go_out=health-monitors/nvswitch-health-monitor/pkg/protos/ --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative --go-grpc_out=health-monitors/nvswitch-health-monitor/pkg/protos/ protobufs/platformconnector.proto
    - protoc -I protobufs/ --go_out=platform-connectors/pkg/connectors/nodehealtheventsudsconnector/protos/ --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative --go-grpc_out=platform-connectors/pkg/connectors/nodehealtheventsudsconnector/protos/ protobufs/nodehealtheventsudsconnector.proto
    - python3 -m grpc_tools.protoc -Iprotobufs/ --python_out=health-monitors/gpu-health-monitor/gpu_health_monitor/platform_connector/protos --pyi_out=health-monitors/gpu-health-monitor/gpu_health_monitor/platform_connector/protos --grpc_python_out=health-monitors/gpu-health-monitor/gpu_health_monitor/platform_connector/protos protobufs/platformconnector.proto
    - python3 -m grpc_tools.protoc -Iprotobufs/ --python_out=health-monitors/gpu-health-monitor/gpu_health_monitor/clear_xid_errors/protos --pyi_out=health-monitors/gpu-health-monitor/gpu_health_monitor/clear_xid_errors/protos --grpc_python_out=health-monitors/gpu-health-monitor/gpu_health_monitor/clear_xid_errors/protos protobufs/platformconnector.proto
    - sed -i 's/^import platformconnector_pb2 as platformconnector__pb2$/from . import platformconnector_pb2 as platformconnector__pb2/' health-monitors/gpu-health-monitor/gpu_health_monitor/platform_connector/protos/platformconnector_pb2_grpc.py # Due to this issue https://github.com/protocolbuffers/protobuf/issues/1491, this needs to be done else it will throw error during execution
    - sed -i 's/^import platformconnector_pb2 as platformconnector__pb2$/from . import platformconnector_pb2 as platformconnector__pb2/' health-monitors/gpu-health-monitor/gpu_health_monitor/clear_xid_errors/protos/platformconnector_pb2_grpc.py # Due to this issue https://github.com/protocolbuffers/protobuf/issues/1491, this needs to be done else it will throw error during execution
    - git status --porcelain
    - git --no-pager diff
    - \[ -z "$(git status --porcelain)" \]

gpu health monitor lint:
  stage: lint
  script:
    - cd health-monitors/gpu-health-monitor
    - poetry install
    - poetry run black --check .

gpu health monitor test:
  stage: test
  script:
    - cd health-monitors/gpu-health-monitor
    - poetry install
    - poetry run coverage run --source=gpu_health_monitor -m pytest -vv --junitxml=report.xml
    - poetry run coverage xml || true
    - poetry run coverage report || true
  artifacts:
    when: always
    reports:
      junit: health-monitors/gpu-health-monitor/report.xml
      coverage_report:
        coverage_format: cobertura
        path: health-monitors/gpu-health-monitor/coverage.xml
  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'

gpu health monitor container publish:
  stage: publish
  image: docker:27.3.1
  services:
    - docker:27.3.1-dind
  before_script:
    - docker info
    - docker login nvcr.io -u ${NGC_USER_NAME} -p ${NGC_PASSWORD}
  script:
    - cd health-monitors/gpu-health-monitor
    - docker context create builder
    - docker buildx create builder --driver-opt network=host --buildkitd-flags '--allow-insecure-entitlement network.host' --use
    - docker buildx build --platform linux/arm64,linux/amd64 --network=host --push -t ${NVCR_CONTAINER_REPO}/${NGC_ORG}/nvsentinel-gpu-health-monitor:${CI_COMMIT_REF_NAME} .
  tags:
    - dind

nic health monitor lint:
  stage: lint
  script:
    - cd health-monitors/nic-health-monitor
    - go vet ./...
    - golangci-lint run
  artifacts:
    when: always
    reports:
      codequality: nic-health-monitor/code-quality-report.json
    paths:
      - nic-health-monitor/code-quality-report.json

nic health monitor test:
  stage: test
  script:
    - cd health-monitors/nic-health-monitor
    - gotestsum --junitfile report.xml -- -race -short $(go list ./... | grep -v pkg/protos) -coverprofile=coverage.txt -covermode atomic
    - go tool cover -func coverage.txt
    - gocover-cobertura < coverage.txt > coverage.xml
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: nic-health-monitor/coverage.xml
      junit: nic-health-monitor/report.xml
  coverage: '/total:\s*\(statements\)\s*\d+.\d+%/'

nic health monitor container publish:
  stage: publish
  image: docker:27.3.1
  services:
    - docker:27.3.1-dind
  before_script:
    - docker info
    - docker login nvcr.io -u ${NGC_USER_NAME} -p ${NGC_PASSWORD}
  script:
    - cd health-monitors/nic-health-monitor
    - docker context create builder
    - docker buildx create builder --driver-opt network=host --buildkitd-flags '--allow-insecure-entitlement network.host' --use
    - docker buildx build --platform linux/arm64,linux/amd64 --network=host --push -t ${NVCR_CONTAINER_REPO}/${NGC_ORG}/nvsentinel-nic-health-monitor:${CI_COMMIT_REF_NAME} .
  tags:
    - dind

nvswitch health monitor lint:
  stage: lint
  script:
    - cd health-monitors/nvswitch-health-monitor
    - go vet ./...
    - golangci-lint run
  artifacts:
    when: always
    reports:
      codequality: nvswitch-health-monitor/code-quality-report.json
    paths:
      - nvswitch-health-monitor/code-quality-report.json

nvswitch health monitor test:
  stage: test
  script:
    - cd health-monitors/nvswitch-health-monitor
    - gotestsum --junitfile report.xml -- -race -short $(go list ./... | grep -v pkg/protos) -coverprofile=coverage.txt -covermode atomic
    - go tool cover -func coverage.txt 
    - gocover-cobertura < coverage.txt > coverage.xml
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: nvswitch-health-monitor/coverage.xml
      junit: nvswitch-health-monitor/report.xml
  coverage: '/total:\s*\(statements\)\s*\d+.\d+%/'

nvswitch health monitor container publish:
  stage: publish
  image: docker:27.3.1
  services:
    - docker:27.3.1-dind
  before_script:
    - docker info
    - docker login nvcr.io -u ${NGC_USER_NAME} -p ${NGC_PASSWORD}
  script:
    - cd health-monitors/nvswitch-health-monitor
    - docker context create builder
    - docker buildx create builder --driver-opt network=host --buildkitd-flags '--allow-insecure-entitlement network.host' --use
    - docker buildx build --platform linux/arm64,linux/amd64 --network=host --push -t ${NVCR_CONTAINER_REPO}/${NGC_ORG}/nvsentinel-nvswitch-health-monitor:${CI_COMMIT_REF_NAME} .
  tags:
    - dind

platform connectors lint:
  stage: lint
  script:
    - cd platform-connectors
    - go vet ./...
    - golangci-lint run
  artifacts:
    when: always
    reports:
      codequality: platform-connectors/code-quality-report.json
    paths:
      - platform-connectors/code-quality-report.json

platform connectors test:
  stage: test
  script:
    - cd platform-connectors
    - gotestsum --junitfile report.xml -- -race -short $(go list ./... | grep -v -e pkg/protos -e pkg/connectors/nodehealtheventsudsconnector/protos) -coverprofile=coverage.txt -covermode atomic
    - go tool cover -func coverage.txt 
    - gocover-cobertura < coverage.txt > coverage.xml
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: platform-connectors/coverage.xml
      junit: platform-connectors/report.xml
  coverage: '/total:\s*\(statements\)\s*\d+.\d+%/'

platform connectors container publish:
  stage: publish
  image: docker:27.3.1
  services:
    - docker:27.3.1-dind
  before_script:
    - docker info
    - docker login nvcr.io -u ${NGC_USER_NAME} -p ${NGC_PASSWORD}
  script:
    - cd platform-connectors
    - docker context create builder
    - docker buildx create builder --driver-opt network=host --buildkitd-flags '--allow-insecure-entitlement network.host' --use
    - docker buildx build --platform linux/arm64,linux/amd64 --network=host --push -t ${NVCR_CONTAINER_REPO}/${NGC_ORG}/nvsentinel-platform-connectors:${CI_COMMIT_REF_NAME} .
  tags:
    - dind

node-health-events-uds connector container publish:
  stage: publish
  image: docker:27.3.1
  services:
    - docker:27.3.1-dind
  before_script:
    - docker info
    - docker login nvcr.io -u ${NGC_USER_NAME} -p ${NGC_PASSWORD}
  script:
    - docker context create builder
    - docker buildx create builder --driver-opt network=host --buildkitd-flags '--allow-insecure-entitlement network.host' --use
    - docker buildx build --platform linux/arm64,linux/amd64 --network=host --push -f distros/container/nvsentinel-node-health-events-distro/Dockerfile -t ${NVCR_CONTAINER_REPO}/${NGC_ORG}/nvsentinel-node-health-events-uds-connector-server:${CI_COMMIT_REF_NAME} .
  tags:
    - dind

store client sdk lint:
  stage: lint
  script:
    - cd store-client-sdk
    - go vet ./...
    - golangci-lint run
  artifacts:
    when: always
    reports:
      codequality: store-client-sdk/code-quality-report.json
    paths:
      - store-client-sdk/code-quality-report.json

store client sdk test:
  stage: test
  script:
    - cd store-client-sdk
    - gotestsum --junitfile report.xml -- -race $(go list ./...) -coverprofile=coverage.txt -covermode atomic
    - go tool cover -func coverage.txt 
    - gocover-cobertura < coverage.txt > coverage.xml
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: store-client-sdk/coverage.xml
      junit: store-client-sdk/report.xml
  coverage: '/total:\s*\(statements\)\s*\d+.\d+%/'

kubernetes distro lint:
  stage: lint
  script:
    - cd distros/kubernetes
    - helm lint nvsentinel/

kubernetes distro helm publish:
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - cd distros/kubernetes
    - helm repo add --force-update ngc ${HELM_URL}/${NGC_ORG} --username=${NGC_USER_NAME} --password=${NGC_PASSWORD}
    - helm repo add --force-update shoreline-agent ${HELM_URL}/${NGC_ORG} --username=${NGC_USER_NAME} --password=${NGC_PASSWORD}
    - cd nvsentinel && helm dependency update && cd ..
    - helm package nvsentinel --version ${CI_COMMIT_TAG}
    - helm cm-push -f nvsentinel-${CI_COMMIT_TAG}.tgz ngc
    - helm repo add --force-update ngc ${HELM_URL}/${NGC_ORG} --username=${NGC_USER_NAME} --password=${NGC_PASSWORD}
    - helm cm-push -f nvsentinel-${CI_COMMIT_TAG}.tgz ngc
