# content of pytest.ini
[pytest]
markers =
    healthcheck: mark a test that only checks the health of the nvsentinel
    smoke: mark a test that only checks the deployment of the nvsentinel
    gpuhealthmonitor: mark a test that only checks the gpu health monitor of the nvsentinel
    nvswitchhealthmonitor: mark a test that only checks the nvswitch health monitor of the nvsentinel
    nichealthmonitor: mark a test that only checks the nic health monitor of the nvsentinel
    sysloghealthmonitor: mark a test that only checks the syslog health monitor of the nvsentinel
    faultquarantine: mark a test that only checks the fault quarantine of the nvsentinel
    nodedrainer: mark a test that only checks the node drainer of the nvsentinel
    metrics: mark a test that only checks the metrics of the nvsentinel
    faultremediation: mark a test that only checks the fault remediation of the nvsentinel
    author: mark a test with author information for tracking purposes
log_cli_level = INFO
log_cli_format = %(asctime)s - %(name)s - %(levelname)s - %(message)s
