nameOverride: ""
fullnameOverride: ""

updateStrategy: RollingUpdate
maxUnavailable: 25%

podAnnotations: {}

podSecurityContext: {}

securityContext:
  runAsUser: 0

resources: 
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector:
  nvidia.com/gpu.present: "true"

tolerations: 
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    operator: Exists

affinity: {}

useHostNetworking: true
metricsPort: 2112
stateFilePath: "/var/run/statefile"