// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.1
// source: devicepluginconnector.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NVIDIADevicePluginConnectorClient is the client API for NVIDIADevicePluginConnector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NVIDIADevicePluginConnectorClient interface {
	HealthEventStreamV1(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (NVIDIADevicePluginConnector_HealthEventStreamV1Client, error)
}

type nVIDIADevicePluginConnectorClient struct {
	cc grpc.ClientConnInterface
}

func NewNVIDIADevicePluginConnectorClient(cc grpc.ClientConnInterface) NVIDIADevicePluginConnectorClient {
	return &nVIDIADevicePluginConnectorClient{cc}
}

func (c *nVIDIADevicePluginConnectorClient) HealthEventStreamV1(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (NVIDIADevicePluginConnector_HealthEventStreamV1Client, error) {
	stream, err := c.cc.NewStream(ctx, &NVIDIADevicePluginConnector_ServiceDesc.Streams[0], "/devicepluginplatformconnector.NVIDIADevicePluginConnector/HealthEventStreamV1", opts...)
	if err != nil {
		return nil, err
	}
	x := &nVIDIADevicePluginConnectorHealthEventStreamV1Client{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NVIDIADevicePluginConnector_HealthEventStreamV1Client interface {
	Recv() (*HealthEvent, error)
	grpc.ClientStream
}

type nVIDIADevicePluginConnectorHealthEventStreamV1Client struct {
	grpc.ClientStream
}

func (x *nVIDIADevicePluginConnectorHealthEventStreamV1Client) Recv() (*HealthEvent, error) {
	m := new(HealthEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NVIDIADevicePluginConnectorServer is the server API for NVIDIADevicePluginConnector service.
// All implementations must embed UnimplementedNVIDIADevicePluginConnectorServer
// for forward compatibility
type NVIDIADevicePluginConnectorServer interface {
	HealthEventStreamV1(*emptypb.Empty, NVIDIADevicePluginConnector_HealthEventStreamV1Server) error
	mustEmbedUnimplementedNVIDIADevicePluginConnectorServer()
}

// UnimplementedNVIDIADevicePluginConnectorServer must be embedded to have forward compatible implementations.
type UnimplementedNVIDIADevicePluginConnectorServer struct {
}

func (UnimplementedNVIDIADevicePluginConnectorServer) HealthEventStreamV1(*emptypb.Empty, NVIDIADevicePluginConnector_HealthEventStreamV1Server) error {
	return status.Errorf(codes.Unimplemented, "method HealthEventStreamV1 not implemented")
}
func (UnimplementedNVIDIADevicePluginConnectorServer) mustEmbedUnimplementedNVIDIADevicePluginConnectorServer() {
}

// UnsafeNVIDIADevicePluginConnectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NVIDIADevicePluginConnectorServer will
// result in compilation errors.
type UnsafeNVIDIADevicePluginConnectorServer interface {
	mustEmbedUnimplementedNVIDIADevicePluginConnectorServer()
}

func RegisterNVIDIADevicePluginConnectorServer(s grpc.ServiceRegistrar, srv NVIDIADevicePluginConnectorServer) {
	s.RegisterService(&NVIDIADevicePluginConnector_ServiceDesc, srv)
}

func _NVIDIADevicePluginConnector_HealthEventStreamV1_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NVIDIADevicePluginConnectorServer).HealthEventStreamV1(m, &nVIDIADevicePluginConnectorHealthEventStreamV1Server{stream})
}

type NVIDIADevicePluginConnector_HealthEventStreamV1Server interface {
	Send(*HealthEvent) error
	grpc.ServerStream
}

type nVIDIADevicePluginConnectorHealthEventStreamV1Server struct {
	grpc.ServerStream
}

func (x *nVIDIADevicePluginConnectorHealthEventStreamV1Server) Send(m *HealthEvent) error {
	return x.ServerStream.SendMsg(m)
}

// NVIDIADevicePluginConnector_ServiceDesc is the grpc.ServiceDesc for NVIDIADevicePluginConnector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NVIDIADevicePluginConnector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "devicepluginplatformconnector.NVIDIADevicePluginConnector",
	HandlerType: (*NVIDIADevicePluginConnectorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HealthEventStreamV1",
			Handler:       _NVIDIADevicePluginConnector_HealthEventStreamV1_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "devicepluginconnector.proto",
}
