apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nic-health-monitor.fullname" . }}
  labels:
    {{- include "nic-health-monitor.labels" . | nindent 4 }}
data:
  config.ini: |
    NicExclusionRegex = ^gketmp.*
    PollingIntervalInMilliseconds = 1000
