apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "nic-health-monitor.fullname" . }}
  labels:
    {{- include "nic-health-monitor.labels" . | nindent 4 }}
spec:
  updateStrategy:
    type: {{ .Values.updateStrategy }}
    {{- if eq .Values.updateStrategy "RollingUpdate"}}
    rollingUpdate:
      maxUnavailable: {{ .Values.maxUnavailable }}
    {{- end}}
  selector:
    matchLabels:
      {{- include "nic-health-monitor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nic-health-monitor.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: nic-health-monitor
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.global.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config-vol
              mountPath: /etc/nichealthmonitor
            - name: var-run-vol
              mountPath: /var/run/
            - name: sys
              mountPath: /sys
              readOnly: true
      volumes:
        - name: var-run-vol
          hostPath:
            path: /var/run/nvsentinel
            type: Directory
        - name: config-vol
          configMap:
            name: {{ include "nic-health-monitor.fullname" . }}
        - name: sys
          hostPath:
            path: /sys
            type: Directory
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
