apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nvsentinel.fullname" . }}
  labels:
    {{- include "nvsentinel.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "nvsentinel.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "nvsentinel.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nvsentinel.fullname" . }}-shoreline
  labels:
    {{- include "nvsentinel.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Namespace }}-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "nvsentinel.fullname" . }}
