apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-connector-configmap
data:
  config.json: |
    {
      "enableK8sPlatformConnector": "true",
      "enableDevicePluginConnector": "true"
    }