apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-connector-configmap
data:
  config.json: |
    {
      "enableK8sPlatformConnector": "{{ .Values.platformConnector.k8sConnector.enabled }}",
      "K8sConnectorQps": {{ printf "%.2f" .Values.platformConnector.k8sConnector.qps }},
      "K8sConnectorBurst": {{ .Values.platformConnector.k8sConnector.burst }},
      "enableNodeHealthEventsUDSConnector": "true",
      "enableMongoDBStorePlatformConnector": "{{ .Values.platformConnector.mongodbStore.enabled }}"
    }