# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: dca-health-monitor-config
  labels:
    {{- include "dca-health-monitor.labels" . | nindent 4 }}
data:
  fars_roles: |
    DRACO_CLUSTER_GPU-H100
    GPU-H100
  healthcheck_conf: |
    fars_host_endpoint: "localhost"
    fars_cache_file: "/tmp/farsroles.txt"
    fars_file_uid: 34000
    fars_file_gid: 30
    fars_static_file: "/etc/healthcheck/default/farsroles.txt"
  cluster_conf: |
    DRACO_CLUSTER_GPU-H100:
      _is_slurm_node: false
      _cluster:
          name: GPU-H100

    GPU-H100:
      # This check is specific to GB200. but not clear on the rationale/remediation part of this check.
      # Clarification is needed from DCA team for this check.
      # sw_sys_logs_qspi_timeout:
      #   path: /nvsentinel/var/log/journal
      #   matches:
      #       - "QSPI Transfer failed with timeout"
      #   count: 0
      #   boot: true
      #   tags:
      #       - "--priority=err"
      #       - "--dmesg"
      #   timeout: 120
      #   _group:
      #     - logs

      sw_sys_logs_nvidia_fabricmanager:
        matches:
          - "Failed to find GPU"
          - " fatal"
        count: 0
        ignore_case: false
        tags:
          - "--boot"
          - "-u nv-fabricmanager.service"
        path: "/nvsentinel/var/log/journal/"
        timeout: 60  # it represents the timeout for the check in seconds
        boot: true
        _group:
          - logs

      sw_sys_logs_nvidia_persistenced:
        matches:
          - "failed to open"
        count: 0
        ignore_case: true
        timeout: 60  # it represents the timeout for the check in seconds
        tags:
          - "--boot"
          - "-u nvidia-persistenced.service"
        path: "/nvsentinel/var/log/journal/"
        boot: true
        _group:
          - logs

      sw_sys_logs_driver_version_mismatch:
        matches:
          - 'Failed to initialize NVML: Driver/library version mismatch'
        count: 0
        ignore_case: false
        timeout: 60  # it represents the timeout for the check in seconds
        tags: []
        path: "/nvsentinel/var/log/journal/"
        boot: false
        _group:
          - logs

      sw_sys_logs_bmc_health:
        matches:
          - 'BMC returned incorrect response'
        count: 4
        ignore_case: true
        timeout: 60  # it represents the timeout for the check in seconds
        tags: []
        path: "/nvsentinel/var/log/journal/"
        boot: false
        _group:
          - logs

      sw_sys_logs_hca_fw_error:
        matches:
          - 'Health issue observed, firmware internal error'
        count: 0
        ignore_case: true
        timeout: 60  # it represents the timeout for the check in seconds
        tags: []
        path: "/nvsentinel/var/log/journal/"
        boot: false
        _group:
          - logs

      sw_sys_logs_ib_firmware_bug:
        matches:
          - 'Skipping wait for vf pages stage'
        count: 0
        ignore_case: false
        timeout: 60  # it represents the timeout for the check in seconds
        tags: []
        path: "/nvsentinel/var/log/journal/"
        boot: false
        _group:
          - logs

      sw_sys_logs_mce_errors:
        matches:
          - 'Machine check events logged'
        count: 20
        ignore_case: true
        timeout: 60  # it represents the timeout for the check in seconds
        tags: []
        path: "/nvsentinel/var/log/journal/"
        boot: false
        _group:
          - logs
