# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: dca-health-monitor-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dca-health-monitor.labels" . | nindent 4 }}
data:
  fars_roles: |
    DRACO_CLUSTER_GPU-H100
    GPU-H100
  healthcheck_conf: |
    fars_host_endpoint: "localhost"
    fars_cache_file: "/tmp/farsroles.txt"
    fars_file_uid: 34000
    fars_file_gid: 30
    fars_static_file: "/etc/healthcheck/default/farsroles.txt"
  cluster_conf: |
    DRACO_CLUSTER_GPU-H100:
      _is_slurm_node: false
      _cluster:
          name: GPU-H100

    GPU-H100:
      hw_drv_gpu_bar1_util:
        max_util: 64
        timeout: 60
        _group:
            - gpu

      hw_drv_gpu_clock_idle:
        idle_util: 0
        idle_mem: 4
        timeout: 60
        _group:
          - gpu

      hw_drv_gpu_compute_apps:
        timeout: 60
        _group:
          - gpu

      hw_drv_gpu_driver_version:
        gpu_driver: "570.86.15"
        count: 8
        timeout: 60
        _group:
          - gpu

      hw_drv_gpu_ecc_error:
        uncorrected_total: 1024000
        corrected_total: 1024000
        uncorrected_total_sram: 1024000
        corrected_total_sram: 1024000
        uncorrected_vol: 3
        corrected_vol: 1024
        timeout: 60
        _group:
          - epilog
          - prolog
          - gpu

      hw_drv_gpu_ecc_remapped_rows:
        correctable_threshold: 1024
        banks_low: 3000
        banks_none: 3000
        banks_partial: 3000
        timeout: 60
        _group:
          - epilog
          - prolog
          - gpu
          
      hw_drv_gpu_ecc_retired_pages:
        timeout: 60
        _group:
          - epilog
          - prolog
          - gpu

      hw_drv_gpu_fw_inforom:
        versions:
          - 'G520.0200.00.05'
        count: 8
        _type: full
        _group:
          - firmware

      hw_drv_gpu_fw_vbios:
        versions:
          - "96.00.A5.00.01"
        count: 8
        _type: full
        _group:
          - firmware

      hw_drv_gpu_power_state:
        timeout: 60
        powerstate: "P0"
        count: 3
        _group:
            - gpu

      hw_drv_gpu_topology:
        timeout: 60
        _group:
          - epilog
          - prolog
          - gpu

      hw_drv_mbd_fw_bios:
        min_version: 'Google'
        expected_version: 'Google'
        _type: full
        _group:
          - firmware

      hw_drv_stor_nvme_fw_version:
        nvme_fw_versions:
            - "2"
        _type: full
        _group:
            - firmware

      hw_drv_stor_nvme_num:
        num: 17
        models:
            - "nvme_card0"
            - "nvme_card1"
            - "nvme_card2"
            - "nvme_card3"
            - "nvme_card4"
            - "nvme_card5"
            - "nvme_card6"
            - "nvme_card7"
            - "nvme_card8"
            - "nvme_card9"
            - "nvme_card10"
            - "nvme_card11"
            - "nvme_card12"
            - "nvme_card13"
            - "nvme_card14"
            - "nvme_card15"
            - "nvme_card-pd"

      hw_drv_stor_nvme_smart:
        settings:
          - "nvme_smart_health_information_log.critical_warning=0"
          - "nvme_smart_health_information_log.available_spare>80"
        disks:
          - "/dev/nvme0n1"
          - "/dev/nvme1n1"
          - "/dev/nvme2n1"
          - "/dev/nvme3n1"
          - "/dev/nvme4n1"
          - "/dev/nvme5n1"
          - "/dev/nvme6n1"
          - "/dev/nvme7n1"
          - "/dev/nvme8n1"
          - "/dev/nvme9n1"
          - "/dev/nvme10n1"
          - "/dev/nvme11n1"
          - "/dev/nvme12n1"
          - "/dev/nvme13n1"
          - "/dev/nvme14n1"
          - "/dev/nvme15n1"
          - "/dev/nvme16n1"

      hw_sys_cpu_count:
        number_cpus: 208
        _type: full

      hw_sys_cpu_numa_cores:
        nps: 2
       
      hw_sys_mem_dimm_count:
        dimm_size: '16 GB'
        dimm_num: 32
        ignore_mismatch: true
        _type: full

      sw_sys_config_nv_container_cli:
        _group:
          - software

      sw_sys_fs_part_free:
        disks:
            - "/=50"

      sw_sys_logs_rminit_adapter:
        path: /nvsentinel/var/log/journal
        matches:
            - "RmInitAdapter failed"
        count: 1
        boot: true
        tags:
            - "--priority=err"
            - "--identifier=kernel"
        timeout: 60
        _group:
            - logs

      sw_sys_logs_qspi_timeout:
        path: /nvsentinel/var/log/journal
        matches:
            - "QSPI Transfer failed with timeout"
        count: 0
        boot: true
        tags:
            - "--priority=err"
            - "--dmesg"
        timeout: 120
        _group:
            - logs

      sw_sys_logs_lustre_error:
        path: /nvsentinel/var/log/journal
        matches:
            - "LNetError: "
            - "LustreError: "
        count: 0
        tags:
            - "--priority=err"
        ignore_case: false
        timeout: 60
        _group:
            - logs

      sw_sys_logs_io_error:
        path: /nvsentinel/var/log/journal
        matches:
            - "I/O error"
        count: 1
        boot: true
        tags:
            - "--priority=err"
            - "--identifier=kernel"
            - "--identifier=systemd"
        timeout: 60
        _group:
            - logs