# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "dca-health-monitor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dca-health-monitor.labels" . | nindent 4 }}
spec:
  updateStrategy:
    type: {{ .Values.updateStrategy | default "RollingUpdate" }}
    {{- if eq (.Values.updateStrategy | default "RollingUpdate") "RollingUpdate"}}
    rollingUpdate:
      maxUnavailable: {{ .Values.maxUnavailable }}
    {{- end}}
  selector:
    matchLabels:
      {{- include "dca-health-monitor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dca-health-monitor.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.dcaHealthMonitor.image.repository }}:{{ .Values.global.dcaHealthMonitor.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.dcaHealthMonitor.image.pullPolicy }}
          command:
            - "/opt/bin/nvsentinel/healthcheck_monitor"
          args:
            - "--interval"
            - "{{ .Values.global.dcaHealthMonitor.interval | default "1800" }}"
          env:
            - name: CLUSTER_NAME
              value: {{ .Values.clusterName }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            # NVSentinel socket location
            - name: var-run-vol
              mountPath: /var/run
            # Host directories for healthchecks
            - name: var-log-vol
              mountPath: /nvsentinel/var/log
            - name: sys-vol
              mountPath: /nvsentinel/sys
            - name: proc-vol
              mountPath: /nvsentinel/proc
            # Configuration files
            - name: cluster-config-vol
              mountPath: /etc/healthcheck/default/clusters/conf_hc_DRACO_CLUSTER_GPU-H100.yml
              subPath: conf_hc_DRACO_CLUSTER_GPU-H100.yml
            - name: fars-config-vol
              mountPath: /etc/healthcheck/default/farsroles.txt
              subPath: farsroles.txt
            - name: hc-config-vol
              mountPath: /etc/healthcheck/default/healthcheck.conf
              subPath: healthcheck.conf
      volumes:
        - name: var-run-vol
          hostPath:
            path: /var/run/nvsentinel
            type: Directory
        # Host directories for tests
        - name: var-log-vol
          hostPath:
            path: /var/log
            type: Directory
        - name: sys-vol
          hostPath:
            path: /sys
        - name: proc-vol
          hostPath:
            path: /proc
            type: Directory
        # Cluster configuration
        - name: cluster-config-vol
          configMap:
            name: dca-health-monitor-config
            items:
            - key: "cluster_conf"
              path: "conf_hc_DRACO_CLUSTER_GPU-H100.yml"
        # FARS configuration
        - name: fars-config-vol
          configMap:
            name: dca-health-monitor-config
            items:
            - key: "fars_roles"
              path: "farsroles.txt"
        # Healthcheck configuration
        - name: hc-config-vol
          configMap:
            name: dca-health-monitor-config
            items:
            - key: "healthcheck_conf"
              path: "healthcheck.conf"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
