# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Pod
metadata:
  name: platform-connector-test-pod
spec:
  nodeSelector:
    kubernetes.io/hostname: "gke-dgxc-runai-us-east5--customer-gpu-42cf53ce-09nn"
  tolerations:
    - effect: NoSchedule
      operator: Exists
    - effect: NoExecute
      operator: Exists
  containers:
  - name: platform-connector-test-pod
    image: nvcr.io/nv-ngc-devops/nvsentinel/platform-connector-testutils:latest
    command: ["sh", "-c", "sleep infinity"]
    imagePullPolicy: Always
    volumeMounts:
      - name: var-run-vol
        mountPath: /var/run/
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
  imagePullSecrets:
    - name: nvidia-ngcuser-pull-secret
  restartPolicy: Never
  volumes:
    - name: var-run-vol
      hostPath:
        path: /var/run/nvsentinel
        type: Directory