// Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.1
// source: nodehealtheventsudsconnector.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// These recommened actions will be aligned with NVML's recommended action
type RecommenedAction int32

const (
	RecommenedAction_NONE                  RecommenedAction = 0
	RecommenedAction_NODE_REBOOT           RecommenedAction = 1
	RecommenedAction_COMPONENT_RESET       RecommenedAction = 2
	RecommenedAction_COMPONENT_REPLACEMENT RecommenedAction = 3
	RecommenedAction_APPLICATION_RESTART   RecommenedAction = 4
	RecommenedAction_REPORT_ISSUE          RecommenedAction = 5
	RecommenedAction_RUN_FIELDDIAG         RecommenedAction = 6
	RecommenedAction_WORKFLOW_XID_13_31    RecommenedAction = 7
	RecommenedAction_WORKFLOW_ECC_DBE_SRAM RecommenedAction = 8
	RecommenedAction_WORKFLOW_NVLINK5_ERR  RecommenedAction = 9
	RecommenedAction_WORKFLOW_XID_45       RecommenedAction = 10
	RecommenedAction_WORKFLOW_XID_48       RecommenedAction = 11
	RecommenedAction_CHECK_MECHANICALS     RecommenedAction = 12
	RecommenedAction_WORKFLOW_NVLINK_ERR   RecommenedAction = 13
	RecommenedAction_UPDATE_SWFW           RecommenedAction = 14
	RecommenedAction_RESTART_VM            RecommenedAction = 15
	RecommenedAction_UNKNOWN               RecommenedAction = 99
)

// Enum value maps for RecommenedAction.
var (
	RecommenedAction_name = map[int32]string{
		0:  "NONE",
		1:  "NODE_REBOOT",
		2:  "COMPONENT_RESET",
		3:  "COMPONENT_REPLACEMENT",
		4:  "APPLICATION_RESTART",
		5:  "REPORT_ISSUE",
		6:  "RUN_FIELDDIAG",
		7:  "WORKFLOW_XID_13_31",
		8:  "WORKFLOW_ECC_DBE_SRAM",
		9:  "WORKFLOW_NVLINK5_ERR",
		10: "WORKFLOW_XID_45",
		11: "WORKFLOW_XID_48",
		12: "CHECK_MECHANICALS",
		13: "WORKFLOW_NVLINK_ERR",
		14: "UPDATE_SWFW",
		15: "RESTART_VM",
		99: "UNKNOWN",
	}
	RecommenedAction_value = map[string]int32{
		"NONE":                  0,
		"NODE_REBOOT":           1,
		"COMPONENT_RESET":       2,
		"COMPONENT_REPLACEMENT": 3,
		"APPLICATION_RESTART":   4,
		"REPORT_ISSUE":          5,
		"RUN_FIELDDIAG":         6,
		"WORKFLOW_XID_13_31":    7,
		"WORKFLOW_ECC_DBE_SRAM": 8,
		"WORKFLOW_NVLINK5_ERR":  9,
		"WORKFLOW_XID_45":       10,
		"WORKFLOW_XID_48":       11,
		"CHECK_MECHANICALS":     12,
		"WORKFLOW_NVLINK_ERR":   13,
		"UPDATE_SWFW":           14,
		"RESTART_VM":            15,
		"UNKNOWN":               99,
	}
)

func (x RecommenedAction) Enum() *RecommenedAction {
	p := new(RecommenedAction)
	*p = x
	return p
}

func (x RecommenedAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecommenedAction) Descriptor() protoreflect.EnumDescriptor {
	return file_nodehealtheventsudsconnector_proto_enumTypes[0].Descriptor()
}

func (RecommenedAction) Type() protoreflect.EnumType {
	return &file_nodehealtheventsudsconnector_proto_enumTypes[0]
}

func (x RecommenedAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecommenedAction.Descriptor instead.
func (RecommenedAction) EnumDescriptor() ([]byte, []int) {
	return file_nodehealtheventsudsconnector_proto_rawDescGZIP(), []int{0}
}

type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entityType,proto3" json:"entityType,omitempty"`
	EntityValue   string                 `protobuf:"bytes,2,opt,name=entityValue,proto3" json:"entityValue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_nodehealtheventsudsconnector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_nodehealtheventsudsconnector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_nodehealtheventsudsconnector_proto_rawDescGZIP(), []int{0}
}

func (x *Entity) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *Entity) GetEntityValue() string {
	if x != nil {
		return x.EntityValue
	}
	return ""
}

type HealthEvents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Events        []*HealthEvent         `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthEvents) Reset() {
	*x = HealthEvents{}
	mi := &file_nodehealtheventsudsconnector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthEvents) ProtoMessage() {}

func (x *HealthEvents) ProtoReflect() protoreflect.Message {
	mi := &file_nodehealtheventsudsconnector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthEvents.ProtoReflect.Descriptor instead.
func (*HealthEvents) Descriptor() ([]byte, []int) {
	return file_nodehealtheventsudsconnector_proto_rawDescGZIP(), []int{1}
}

func (x *HealthEvents) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *HealthEvents) GetEvents() []*HealthEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type HealthEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Version            uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	CheckName          string                 `protobuf:"bytes,2,opt,name=checkName,proto3" json:"checkName,omitempty"`                                                                             // name of the check that was executed
	IsFatal            bool                   `protobuf:"varint,3,opt,name=isFatal,proto3" json:"isFatal,omitempty"`                                                                                // if the health event is fatal
	IsHealthy          bool                   `protobuf:"varint,4,opt,name=isHealthy,proto3" json:"isHealthy,omitempty"`                                                                            // is the component healthy
	Message            string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`                                                                                 // user friendly message
	RecommendedAction  RecommenedAction       `protobuf:"varint,6,opt,name=recommendedAction,proto3,enum=nodehealtheventsudsplatformconnector.RecommenedAction" json:"recommendedAction,omitempty"` // recommended action for remediation
	ErrorCode          []string               `protobuf:"bytes,7,rep,name=errorCode,proto3" json:"errorCode,omitempty"`                                                                             // list of machine readable error code
	ImpactedIndices    []*Entity              `protobuf:"bytes,8,rep,name=impactedIndices,proto3" json:"impactedIndices,omitempty"`                                                                 // list of GPUs impacted by the error
	Metadata           map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`     // metadata about the event
	GeneratedTimestamp *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=generatedTimestamp,proto3" json:"generatedTimestamp,omitempty"`                                                          // timestamp when the event was generated
	NodeName           string                 `protobuf:"bytes,11,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HealthEvent) Reset() {
	*x = HealthEvent{}
	mi := &file_nodehealtheventsudsconnector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthEvent) ProtoMessage() {}

func (x *HealthEvent) ProtoReflect() protoreflect.Message {
	mi := &file_nodehealtheventsudsconnector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthEvent.ProtoReflect.Descriptor instead.
func (*HealthEvent) Descriptor() ([]byte, []int) {
	return file_nodehealtheventsudsconnector_proto_rawDescGZIP(), []int{2}
}

func (x *HealthEvent) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *HealthEvent) GetCheckName() string {
	if x != nil {
		return x.CheckName
	}
	return ""
}

func (x *HealthEvent) GetIsFatal() bool {
	if x != nil {
		return x.IsFatal
	}
	return false
}

func (x *HealthEvent) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

func (x *HealthEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthEvent) GetRecommendedAction() RecommenedAction {
	if x != nil {
		return x.RecommendedAction
	}
	return RecommenedAction_NONE
}

func (x *HealthEvent) GetErrorCode() []string {
	if x != nil {
		return x.ErrorCode
	}
	return nil
}

func (x *HealthEvent) GetImpactedIndices() []*Entity {
	if x != nil {
		return x.ImpactedIndices
	}
	return nil
}

func (x *HealthEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *HealthEvent) GetGeneratedTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedTimestamp
	}
	return nil
}

func (x *HealthEvent) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

var File_nodehealtheventsudsconnector_proto protoreflect.FileDescriptor

const file_nodehealtheventsudsconnector_proto_rawDesc = "" +
	"\n" +
	"\"nodehealtheventsudsconnector.proto\x12$nodehealtheventsudsplatformconnector\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"J\n" +
	"\x06Entity\x12\x1e\n" +
	"\n" +
	"entityType\x18\x01 \x01(\tR\n" +
	"entityType\x12 \n" +
	"\ventityValue\x18\x02 \x01(\tR\ventityValue\"s\n" +
	"\fHealthEvents\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12I\n" +
	"\x06events\x18\x02 \x03(\v21.nodehealtheventsudsplatformconnector.HealthEventR\x06events\"\xf5\x04\n" +
	"\vHealthEvent\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1c\n" +
	"\tcheckName\x18\x02 \x01(\tR\tcheckName\x12\x18\n" +
	"\aisFatal\x18\x03 \x01(\bR\aisFatal\x12\x1c\n" +
	"\tisHealthy\x18\x04 \x01(\bR\tisHealthy\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12d\n" +
	"\x11recommendedAction\x18\x06 \x01(\x0e26.nodehealtheventsudsplatformconnector.RecommenedActionR\x11recommendedAction\x12\x1c\n" +
	"\terrorCode\x18\a \x03(\tR\terrorCode\x12V\n" +
	"\x0fimpactedIndices\x18\b \x03(\v2,.nodehealtheventsudsplatformconnector.EntityR\x0fimpactedIndices\x12[\n" +
	"\bmetadata\x18\t \x03(\v2?.nodehealtheventsudsplatformconnector.HealthEvent.MetadataEntryR\bmetadata\x12J\n" +
	"\x12generatedTimestamp\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x12generatedTimestamp\x12\x1a\n" +
	"\bnodeName\x18\v \x01(\tR\bnodeName\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xf0\x02\n" +
	"\x10RecommenedAction\x12\b\n" +
	"\x04NONE\x10\x00\x12\x0f\n" +
	"\vNODE_REBOOT\x10\x01\x12\x13\n" +
	"\x0fCOMPONENT_RESET\x10\x02\x12\x19\n" +
	"\x15COMPONENT_REPLACEMENT\x10\x03\x12\x17\n" +
	"\x13APPLICATION_RESTART\x10\x04\x12\x10\n" +
	"\fREPORT_ISSUE\x10\x05\x12\x11\n" +
	"\rRUN_FIELDDIAG\x10\x06\x12\x16\n" +
	"\x12WORKFLOW_XID_13_31\x10\a\x12\x19\n" +
	"\x15WORKFLOW_ECC_DBE_SRAM\x10\b\x12\x18\n" +
	"\x14WORKFLOW_NVLINK5_ERR\x10\t\x12\x13\n" +
	"\x0fWORKFLOW_XID_45\x10\n" +
	"\x12\x13\n" +
	"\x0fWORKFLOW_XID_48\x10\v\x12\x15\n" +
	"\x11CHECK_MECHANICALS\x10\f\x12\x17\n" +
	"\x13WORKFLOW_NVLINK_ERR\x10\r\x12\x0f\n" +
	"\vUPDATE_SWFW\x10\x0e\x12\x0e\n" +
	"\n" +
	"RESTART_VM\x10\x0f\x12\v\n" +
	"\aUNKNOWN\x10c2\x85\x01\n" +
	"\x1cNodeHealthEventsUDSConnector\x12e\n" +
	"\x13HealthEventStreamV1\x12\x16.google.protobuf.Empty\x1a2.nodehealtheventsudsplatformconnector.HealthEvents\"\x000\x01B\x86\x01Z\x83\x01gitlab-master.nvidia.com/dgxcloud/mk8s/k8s-addons/nvsentinel/platform-connectors/pkg/connectors/nodehealtheventsudsconnector/protosb\x06proto3"

var (
	file_nodehealtheventsudsconnector_proto_rawDescOnce sync.Once
	file_nodehealtheventsudsconnector_proto_rawDescData []byte
)

func file_nodehealtheventsudsconnector_proto_rawDescGZIP() []byte {
	file_nodehealtheventsudsconnector_proto_rawDescOnce.Do(func() {
		file_nodehealtheventsudsconnector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nodehealtheventsudsconnector_proto_rawDesc), len(file_nodehealtheventsudsconnector_proto_rawDesc)))
	})
	return file_nodehealtheventsudsconnector_proto_rawDescData
}

var file_nodehealtheventsudsconnector_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nodehealtheventsudsconnector_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_nodehealtheventsudsconnector_proto_goTypes = []any{
	(RecommenedAction)(0),         // 0: nodehealtheventsudsplatformconnector.RecommenedAction
	(*Entity)(nil),                // 1: nodehealtheventsudsplatformconnector.Entity
	(*HealthEvents)(nil),          // 2: nodehealtheventsudsplatformconnector.HealthEvents
	(*HealthEvent)(nil),           // 3: nodehealtheventsudsplatformconnector.HealthEvent
	nil,                           // 4: nodehealtheventsudsplatformconnector.HealthEvent.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
}
var file_nodehealtheventsudsconnector_proto_depIdxs = []int32{
	3, // 0: nodehealtheventsudsplatformconnector.HealthEvents.events:type_name -> nodehealtheventsudsplatformconnector.HealthEvent
	0, // 1: nodehealtheventsudsplatformconnector.HealthEvent.recommendedAction:type_name -> nodehealtheventsudsplatformconnector.RecommenedAction
	1, // 2: nodehealtheventsudsplatformconnector.HealthEvent.impactedIndices:type_name -> nodehealtheventsudsplatformconnector.Entity
	4, // 3: nodehealtheventsudsplatformconnector.HealthEvent.metadata:type_name -> nodehealtheventsudsplatformconnector.HealthEvent.MetadataEntry
	5, // 4: nodehealtheventsudsplatformconnector.HealthEvent.generatedTimestamp:type_name -> google.protobuf.Timestamp
	6, // 5: nodehealtheventsudsplatformconnector.NodeHealthEventsUDSConnector.HealthEventStreamV1:input_type -> google.protobuf.Empty
	2, // 6: nodehealtheventsudsplatformconnector.NodeHealthEventsUDSConnector.HealthEventStreamV1:output_type -> nodehealtheventsudsplatformconnector.HealthEvents
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_nodehealtheventsudsconnector_proto_init() }
func file_nodehealtheventsudsconnector_proto_init() {
	if File_nodehealtheventsudsconnector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nodehealtheventsudsconnector_proto_rawDesc), len(file_nodehealtheventsudsconnector_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nodehealtheventsudsconnector_proto_goTypes,
		DependencyIndexes: file_nodehealtheventsudsconnector_proto_depIdxs,
		EnumInfos:         file_nodehealtheventsudsconnector_proto_enumTypes,
		MessageInfos:      file_nodehealtheventsudsconnector_proto_msgTypes,
	}.Build()
	File_nodehealtheventsudsconnector_proto = out.File
	file_nodehealtheventsudsconnector_proto_goTypes = nil
	file_nodehealtheventsudsconnector_proto_depIdxs = nil
}
