// Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.1
// source: nodehealtheventsudsconnector.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NodeHealthEventsUDSConnector_HealthEventStreamV1_FullMethodName = "/nodehealtheventsudsplatformconnector.NodeHealthEventsUDSConnector/HealthEventStreamV1"
)

// NodeHealthEventsUDSConnectorClient is the client API for NodeHealthEventsUDSConnector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeHealthEventsUDSConnectorClient interface {
	HealthEventStreamV1(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (NodeHealthEventsUDSConnector_HealthEventStreamV1Client, error)
}

type nodeHealthEventsUDSConnectorClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeHealthEventsUDSConnectorClient(cc grpc.ClientConnInterface) NodeHealthEventsUDSConnectorClient {
	return &nodeHealthEventsUDSConnectorClient{cc}
}

func (c *nodeHealthEventsUDSConnectorClient) HealthEventStreamV1(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (NodeHealthEventsUDSConnector_HealthEventStreamV1Client, error) {
	stream, err := c.cc.NewStream(ctx, &NodeHealthEventsUDSConnector_ServiceDesc.Streams[0], NodeHealthEventsUDSConnector_HealthEventStreamV1_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &nodeHealthEventsUDSConnectorHealthEventStreamV1Client{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NodeHealthEventsUDSConnector_HealthEventStreamV1Client interface {
	Recv() (*HealthEvents, error)
	grpc.ClientStream
}

type nodeHealthEventsUDSConnectorHealthEventStreamV1Client struct {
	grpc.ClientStream
}

func (x *nodeHealthEventsUDSConnectorHealthEventStreamV1Client) Recv() (*HealthEvents, error) {
	m := new(HealthEvents)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NodeHealthEventsUDSConnectorServer is the server API for NodeHealthEventsUDSConnector service.
// All implementations must embed UnimplementedNodeHealthEventsUDSConnectorServer
// for forward compatibility
type NodeHealthEventsUDSConnectorServer interface {
	HealthEventStreamV1(*emptypb.Empty, NodeHealthEventsUDSConnector_HealthEventStreamV1Server) error
	mustEmbedUnimplementedNodeHealthEventsUDSConnectorServer()
}

// UnimplementedNodeHealthEventsUDSConnectorServer must be embedded to have forward compatible implementations.
type UnimplementedNodeHealthEventsUDSConnectorServer struct {
}

func (UnimplementedNodeHealthEventsUDSConnectorServer) HealthEventStreamV1(*emptypb.Empty, NodeHealthEventsUDSConnector_HealthEventStreamV1Server) error {
	return status.Errorf(codes.Unimplemented, "method HealthEventStreamV1 not implemented")
}
func (UnimplementedNodeHealthEventsUDSConnectorServer) mustEmbedUnimplementedNodeHealthEventsUDSConnectorServer() {
}

// UnsafeNodeHealthEventsUDSConnectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeHealthEventsUDSConnectorServer will
// result in compilation errors.
type UnsafeNodeHealthEventsUDSConnectorServer interface {
	mustEmbedUnimplementedNodeHealthEventsUDSConnectorServer()
}

func RegisterNodeHealthEventsUDSConnectorServer(s grpc.ServiceRegistrar, srv NodeHealthEventsUDSConnectorServer) {
	s.RegisterService(&NodeHealthEventsUDSConnector_ServiceDesc, srv)
}

func _NodeHealthEventsUDSConnector_HealthEventStreamV1_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeHealthEventsUDSConnectorServer).HealthEventStreamV1(m, &nodeHealthEventsUDSConnectorHealthEventStreamV1Server{stream})
}

type NodeHealthEventsUDSConnector_HealthEventStreamV1Server interface {
	Send(*HealthEvents) error
	grpc.ServerStream
}

type nodeHealthEventsUDSConnectorHealthEventStreamV1Server struct {
	grpc.ServerStream
}

func (x *nodeHealthEventsUDSConnectorHealthEventStreamV1Server) Send(m *HealthEvents) error {
	return x.ServerStream.SendMsg(m)
}

// NodeHealthEventsUDSConnector_ServiceDesc is the grpc.ServiceDesc for NodeHealthEventsUDSConnector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeHealthEventsUDSConnector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nodehealtheventsudsplatformconnector.NodeHealthEventsUDSConnector",
	HandlerType: (*NodeHealthEventsUDSConnectorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HealthEventStreamV1",
			Handler:       _NodeHealthEventsUDSConnector_HealthEventStreamV1_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nodehealtheventsudsconnector.proto",
}
