apiVersion: v1
kind: Pod
metadata:
  name: nvsentinel-device-plugin-connector-client
  namespace: nvsentinel
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchFields:
              - key: metadata.name
                operator: In
                values:
                  - minikube
  containers:
  - image: nvcr.io/nv-ngc-devops/nvsentinel-device-plugin-connector-client:main
    imagePullPolicy: IfNotPresent
    name: device-plugin-connector-client
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 512Mi
    securityContext:
      capabilities:
        drop:
         - ALL
      runAsUser: 0
    volumeMounts:
    - mountPath: /var/run
      name: var-run-vol
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: nvidia-ngcuser-pull-secret
  restartPolicy: Always
  securityContext: {}
  terminationGracePeriodSeconds: 30
  tolerations:
  - operator: Exists
  volumes:
    - hostPath:
        path: /var/run/nvsentinel
        type: DirectoryOrCreate
      name: var-run-vol