replicaCount: 0

image:
  repository: nvcr.io/nv-ngc-devops/nvsentinel/example-health-monitor
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: nvidia-ngcuser-pull-secret

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  runAsUser: 0
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}