# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: nvsentinel-gitlab-tag-sensor
  namespace: nvsentinel-system
spec:
  eventBusName: default
  template:
    serviceAccountName: nvsentinel-workflow-sa
  eventCorrelation:
    strategy: "Expression"
    expression: "{{ .Input.body.after }}"
  dependencies:
  - name: gitlab-tag-dep
    eventSourceName: nvsentinel-gitlab-events
    eventName: nvsentinel-tags
    filters:
      data:
      - path: body.object_kind
        type: string
        value:
        - "tag_push"
      - path: body.before
        type: string
        value:
        - "0000000000000000000000000000000000000000"
  - name: gitlab-pipeline-success-dep
    eventSourceName: nvsentinel-gitlab-events
    eventName: nvsentinel-pipelines
    filters:
      data:
      - path: body.object_kind
        type: string
        value: ["pipeline"]
      - path: body.object_attributes.status
        type: string
        value: ["success"]
      - path: body.object_attributes.tag
        type: bool
        value: [true]

  circuit: false
  dependencyGroups:
  - name: tag-and-pipeline-ok
    dependencies:
    - gitlab-tag-dep
    - gitlab-pipeline-success-dep
  triggers:
  - template:
      name: nvsentinel-deployment-trigger
      argoWorkflow:
        operation: submit
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: nvsentinel-deploy-webhook-
              namespace: nvsentinel-system
              labels:
                triggered-by: webhook
            spec:
              serviceAccountName: nvsentinel-workflow-sa
              workflowTemplateRef:
                name: nvsentinel-deployment
              arguments:
                parameters:
                - name: version
                  value: ""
                - name: commit-sha
                  value: ""
                - name: timestamp
                  value: ""
                - name: user_id
                  value: ""
              ttlStrategy:
                secondsAfterCompletion: 86400
              podGC:
                strategy: OnWorkflowCompletion
        parameters:
        - src:
            dependencyName: gitlab-tag-dep
            dataTemplate: "{{ .Input.body.ref | replace \"refs/tags/\" \"\" }}"
          dest: spec.arguments.parameters.0.value
        - src:
            dependencyName: gitlab-tag-dep
            dataKey: body.after
          dest: spec.arguments.parameters.1.value
        - src:
            dependencyName: gitlab-tag-dep
            dataTemplate: "{{ .Input.body.timestamp | default now }}"
          dest: spec.arguments.parameters.2.value
        - src:
            dependencyName: gitlab-tag-dep
            dataKey: body.user_id
          dest: spec.arguments.parameters.3.value