apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gpu-health-monitor.fullname" . }}
  labels:
    {{- include "gpu-health-monitor.labels" . | nindent 4 }}
data:
  config.ini: |
    [logging]
    LogFormat = %%(asctime)s,%%(msecs)03d %%(levelname)-8s [%%(filename)s:%%(lineno)d] %%(message)s
    DateTimeFormat = %%Y-%%m-%%d:%%H:%%M:%%S

    [dcgm]
    PollIntervalSeconds = 15
    FieldsToMonitor = DCGM_FI_DEV_RETIRED_SBE,DCGM_FI_DEV_RETIRED_DBE,DCGM_FI_DEV_RETIRED_PENDING,DCGM_FI_DEV_UNCORRECTABLE_REMAPPED_ROWS,DCGM_FI_DEV_CORRECTABLE_REMAPPED_ROWS,DCGM_FI_DEV_ROW_REMAP_FAILURE,DCGM_FI_DEV_ROW_REMAP_PENDING

    [eventprocessors.kubernetes]
    ConflictRetryCount = 10
    FatalXidErrors = 63,64,93

    [eventprocessors.platformconnector]
    SocketPath = /var/run/nvsentinel.sock

    [cli]
    EnabledEventProcessors = PlatformConnectorEventProcessor

    [xiderrorrecommendactiontoplatformconnectormapping]
    UNEXPECTED_ERR_REPORT_ISSUE = 5
    WORKFLOW_XID_13_31 = 99
    IGNORE = 0
    WORKFLOW_ECC_DBE_SRAM = 99
    REPORT_ISSUE = 5
    RUN_FIELDDIAG = 6
    WORKFLOW_NVLINK_ERR = 99
    RESTART_APP = 4
    RESET_GPU = 2
    RESOLUTION_BUCKET_TBD = 99
    WORKFLOW_NVLINK5_ERR = 99

  # The below tables should map to the xid error spreadsheet https://docs.google.com/spreadsheets/d/1t6PpsC5TXiNl4JMBuHlFIjmSbjLZ2ik0Sz3DLw8cLmE/edit?gid=121017179#gid=121017179
  #ordering of below columns => xiderrorno,xiderrorname,xiderrorrecommendedaction,FATAL/NONFATAL errors
  xiderrorsmapping.csv: |
    1,ROBUST_CHANNEL_FIFO_ERROR_FIFO_METHOD,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    2,ROBUST_CHANNEL_FIFO_ERROR_SW_METHOD,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    3,ROBUST_CHANNEL_FIFO_ERROR_UNK_METHOD,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    4,ROBUST_CHANNEL_FIFO_ERROR_CHANNEL_BUSY,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    5,ROBUST_CHANNEL_FIFO_ERROR_RUNOUT_OVERFLOW,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    6,ROBUST_CHANNEL_FIFO_ERROR_PARSE_ERR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    7,ROBUST_CHANNEL_FIFO_ERROR_PTE_ERR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    8,ROBUST_CHANNEL_FIFO_ERROR_IDLE_TIMEOUT,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    9,ROBUST_CHANNEL_GR_ERROR_INSTANCE,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    10,ROBUST_CHANNEL_GR_ERROR_SINGLE_STEP,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    11,ROBUST_CHANNEL_GR_ERROR_MISSING_HW,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    12,ROBUST_CHANNEL_GR_ERROR_SW_METHOD,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    13,ROBUST_CHANNEL_GR_ERROR_SW_NOTIFY,WORKFLOW_XID_13_31,FATAL
    14,,IGNORE,NONFATAL
    15,ROBUST_CHANNEL_SCANLINE_TIMEOUT,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    16,ROBUST_CHANNEL_FAKE_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    17,ROBUST_CHANNEL_PARAMETER_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    18,ROBUST_CHANNEL_BUS_MASTER_TIMEOUT_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    19,ROBUST_CHANNEL_DISP_MISSED_NOTIFIER,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    20,ROBUST_CHANNEL_MPEG_ERROR_SW_METHOD,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    21,ROBUST_CHANNEL_ME_ERROR_SW_METHOD,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    22,ROBUST_CHANNEL_VP_ERROR_SW_METHOD,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    23,ROBUST_CHANNEL_RC_LOGGING_ENABLED,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    24,ROBUST_CHANNEL_GR_SEMAPHORE_TIMEOUT,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    25,ROBUST_CHANNEL_GR_ILLEGAL_NOTIFY,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    26,ROBUST_CHANNEL_FIFO_ERROR_FBISTATE_TIMEOUT,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    27,ROBUST_CHANNEL_VP_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    28,ROBUST_CHANNEL_VP2_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    29,ROBUST_CHANNEL_BSP_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    30,ROBUST_CHANNEL_BAD_ADDR_ACCESS,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    31,ROBUST_CHANNEL_FIFO_ERROR_MMU_ERR_FLT,WORKFLOW_XID_13_31,FATAL
    32,ROBUST_CHANNEL_PBDMA_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    33,ROBUST_CHANNEL_SEC_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    34,ROBUST_CHANNEL_MSVLD_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    35,ROBUST_CHANNEL_MSPDEC_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    36,ROBUST_CHANNEL_MSPPP_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    37,ROBUST_CHANNEL_FECS_ERR_UNIMP_FIRMWARE_METHOD,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    38,ROBUST_CHANNEL_FECS_ERR_WATCHDOG_TIMEOUT,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    39,ROBUST_CHANNEL_CE0_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    40,ROBUST_CHANNEL_CE1_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    41,ROBUST_CHANNEL_CE2_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    42,ROBUST_CHANNEL_VIC_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    43,ROBUST_CHANNEL_RESETCHANNEL_VERIF_ERROR,IGNORE,NONFATAL
    44,ROBUST_CHANNEL_GR_FAULT_DURING_CTXSW,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    45,ROBUST_CHANNEL_PREEMPTIVE_REMOVAL,IGNORE,NONFATAL
    46,ROBUST_CHANNEL_GPU_TIMEOUT_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    47,ROBUST_CHANNEL_NVENC0_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    48,ROBUST_CHANNEL_GPU_ECC_DBE,WORKFLOW_ECC_DBE_SRAM,FATAL
    49,SILENT_RUNNING_CONSTANT_LEVEL_SET_BY_REGISTRY,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    50,SILENT_RUNNING_LEVEL_TRANSITION_DUE_TO_RC_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    51,SILENT_RUNNING_STRESS_TEST_FAILURE,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    52,SILENT_RUNNING_LEVEL_TRANS_DUE_TO_TEMP_RISE,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    53,SILENT_RUNNING_TEMP_REDUCED_CLOCKING,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    54,SILENT_RUNNING_PWR_REDUCED_CLOCKING,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    55,SILENT_RUNNING_TEMPERATURE_READ_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    56,DISPLAY_CHANNEL_EXCEPTION,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    57,FB_LINK_TRAINING_FAILURE_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    58,FB_MEMORY_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    59,PMU_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    60,ROBUST_CHANNEL_SEC2_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    61,PMU_BREAKPOINT,REPORT_ISSUE,FATAL
    62,PMU_HALT_ERROR,REPORT_ISSUE,FATAL
    63,INFOROM_DRAM_RETIREMENT_EVENT,IGNORE,NONFATAL
    64,INFOROM_DRAM_RETIREMENT_FAILURE,RUN_FIELDDIAG,FATAL
    65,ROBUST_CHANNEL_NVENC1_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    66,ROBUST_CHANNEL_FECS_ERR_REG_ACCESS_VIOLATION,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    67,ROBUST_CHANNEL_FECS_ERR_VERIF_VIOLATION,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    68,ROBUST_CHANNEL_NVDEC0_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    69,ROBUST_CHANNEL_GR_CLASS_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    70,ROBUST_CHANNEL_CE3_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    71,ROBUST_CHANNEL_CE4_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    72,ROBUST_CHANNEL_CE5_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    73,ROBUST_CHANNEL_NVENC2_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    74,NVLINK_ERROR,WORKFLOW_NVLINK_ERR,FATAL
    75,ROBUST_CHANNEL_CE6_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    76,ROBUST_CHANNEL_CE7_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    77,ROBUST_CHANNEL_CE8_ERROR,ROBUST_CHANNEL_CE8_ERROR,FATAL
    78,VGPU_START_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    79,ROBUST_CHANNEL_GPU_HAS_FALLEN_OFF_THE_BUS,RUN_FIELDDIAG,FATAL
    80,PBDMA_PUSHBUFFER_CRC_MISMATCH,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    81,ROBUST_CHANNEL_VGA_SUBSYSTEM_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    82,ROBUST_CHANNEL_NVJPG0_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    83,ROBUST_CHANNEL_NVDEC1_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    84,ROBUST_CHANNEL_NVDEC2_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    85,ROBUST_CHANNEL_CE9_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    86,ROBUST_CHANNEL_OFA0_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    87,NVTELEMETRY_DRIVER_REPORT,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    88,ROBUST_CHANNEL_NVDEC3_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    89,ROBUST_CHANNEL_NVDEC4_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    90,LTC_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    91,RESERVED_XID,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    92,EXCESSIVE_SBE_INTERRUPTS,RUN_FIELDDIAG,FATAL
    93,INFOROM_ERASE_LIMIT_EXCEEDED,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    94,ROBUST_CHANNEL_CONTAINED_ERROR,RESTART_APP,FATAL
    95,ROBUST_CHANNEL_UNCONTAINED_ERROR,RESET_GPU,FATAL
    96,ROBUST_CHANNEL_NVDEC5_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    97,ROBUST_CHANNEL_NVDEC6_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    98,ROBUST_CHANNEL_NVDEC7_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    99,ROBUST_CHANNEL_NVJPG1_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    100,ROBUST_CHANNEL_NVJPG2_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    101,ROBUST_CHANNEL_NVJPG3_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    102,ROBUST_CHANNEL_NVJPG4_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    103,ROBUST_CHANNEL_NVJPG5_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    104,ROBUST_CHANNEL_NVJPG6_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    105,ROBUST_CHANNEL_NVJPG7_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    106,SMBPBI_TEST_MESSAGE,IGNORE,NONFATAL
    107,SMBPBI_TEST_MESSAGE_SILENT,IGNORE,NONFATAL
    108,DESTINATION_FLA_TRANSLATION_ERROR,RESOLUTION_BUCKET_TBD,FATAL
    109,ROBUST_CHANNEL_CTXSW_TIMEOUT_ERROR,REPORT_ISSUE,FATAL
    110,SEC_FAULT_ERROR,RESOLUTION_BUCKET_TBD,FATAL
    111,BUNDLE_ERROR_EVENT,RESOLUTION_BUCKET_TBD,FATAL
    112,DISP_SUPERVISOR_ERROR,RESOLUTION_BUCKET_TBD,FATAL
    113,DP_LT_FAILURE,RESOLUTION_BUCKET_TBD,FATAL
    114,HEAD_RG_UNDERFLOW,RESOLUTION_BUCKET_TBD,FATAL
    115,CORE_CHANNEL_REGS,RESOLUTION_BUCKET_TBD,FATAL
    116,WINDOW_CHANNEL_REGS,RESOLUTION_BUCKET_TBD,FATAL
    117,CURSOR_CHANNEL_REGS,RESOLUTION_BUCKET_TBD,FATAL
    118,HEAD_REGS,RESOLUTION_BUCKET_TBD,FATAL
    119,GSP_RPC_TIMEOUT,REPORT_ISSUE,FATAL
    120,GSP_ERROR,REPORT_ISSUE,REPORT_ISSUE,FATAL
    121,C2C_ERROR,RESET_GPU,FATAL
    123,SPI_PMU_RPC_READ_FAIL,REPORT_ISSUE,FATAL
    124,SPI_PMU_RPC_WRITE_FAIL,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    125,INFOROM_FS_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    126,ROBUST_CHANNEL_CE10_ERROR,RESOLUTION_BUCKET_TBD,FATAL
    127,ROBUST_CHANNEL_CE11_ERROR,RESOLUTION_BUCKET_TBD,FATAL
    128,ROBUST_CHANNEL_CE12_ERROR,RESOLUTION_BUCKET_TBD,FATAL
    129,ROBUST_CHANNEL_CE13_ERROR,RESOLUTION_BUCKET_TBD,FATAL
    130,ROBUST_CHANNEL_CE14_ERROR,RESOLUTION_BUCKET_TBD,FATAL
    131,ROBUST_CHANNEL_CE15_ERROR,RESOLUTION_BUCKET_TBD,FATAL
    132,ROBUST_CHANNEL_CE16_ERROR,RESOLUTION_BUCKET_TBD,FATAL
    133,ROBUST_CHANNEL_CE17_ERROR,RESOLUTION_BUCKET_TBD,FATAL
    134,ROBUST_CHANNEL_CE18_ERROR,RESOLUTION_BUCKET_TBD,FATAL
    135,ROBUST_CHANNEL_CE19_ERROR,RESOLUTION_BUCKET_TBD,FATAL
    136,ALI_TRAINING_FAIL,RESOLUTION_BUCKET_TBD,FATAL
    137,NVLINK_FLA_PRIV_ERR,RESOLUTION_BUCKET_TBD,FATAL
    138,ROBUST_CHANNEL_DLA_ERROR,RESOLUTION_BUCKET_TBD,FATAL
    139,ROBUST_CHANNEL_OFA1_ERROR,RESOLUTION_BUCKET_TBD,FATAL
    140,UNRECOVERABLE_ECC_ERROR_ESCAPE,RESET_GPU,FATAL
    141,ROBUST_CHANNEL_FAST_PATH_ERROR,RESOLUTION_BUCKET_TBD,FATAL
    142,ROBUST_CHANNEL_NVENC3_ERROR,UNEXPECTED_ERR_REPORT_ISSUE,FATAL
    143,GPU_INIT_ERROR,RUN_FIELDDIAG,FATAL
    144,NVLINK_SAW_ERROR,WORKFLOW_NVLINK5_ERR,FATAL
    145,NVLINK_RLW_ERROR,WORKFLOW_NVLINK5_ERR,FATAL
    146,NVLINK_TLW_ERROR,WORKFLOW_NVLINK5_ERR,FATAL
    147,NVLINK_TREX_ERROR,WORKFLOW_NVLINK5_ERR,FATAL
    148,NVLINK_NVLPW_CTRL_ERROR,WORKFLOW_NVLINK5_ERR,FATAL
    149,NVLINK_NETIR_ERROR,WORKFLOW_NVLINK5_ERR,FATAL
    150,NVLINK_MSE_ERROR,WORKFLOW_NVLINK5_ERR,FATAL
    151,ROBUST_CHANNEL_KEY_ROTATION_ERROR,RESOLUTION_BUCKET_TBD,FATAL
    152,ROBUST_CHANNEL_DLA_SMMU_ERROR,RESOLUTION_BUCKET_TBD,FATAL
    153,ROBUST_CHANNEL_DLA_TIMEOUT,RESOLUTION_BUCKET_TBD,FATAL


