# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gpu-health-monitor.fullname" . }}
  labels:
    {{- include "gpu-health-monitor.labels" . | nindent 4 }}
data:
  config.ini: |
    [logging]
    LogFormat = %%(asctime)s,%%(msecs)03d %%(levelname)-8s [%%(filename)s:%%(lineno)d] %%(message)s
    DateTimeFormat = %%Y-%%m-%%d:%%H:%%M:%%S

    [dcgm]
    PollIntervalSeconds = 15

    [eventprocessors.kubernetes]
    ConflictRetryCount = 10
    FatalXidErrors = 63,64,93

    [eventprocessors.platformconnector]
    SocketPath = /var/run/nvsentinel.sock

    [cli]
    EnabledEventProcessors = PlatformConnectorEventProcessor
    
    [xiderrorsconfig]
    XidErrorsBatchProcessingEnabled = false
    XidErrorsSlidingWindowSize = 3
    XidErrorsBatchProcessingInterval = 10

    [xiderrorrecommendactiontoplatformconnectormapping]
    UNEXPECTED_ERR_REPORT_ISSUE = 5
    WORKFLOW_XID_13_31 = 7
    IGNORE = 0
    WORKFLOW_ECC_DBE_SRAM = 8
    REPORT_ISSUE = 5
    RUN_FIELDDIAG = 6
    RESTART_APP = 4
    RESET_GPU = 2
    RESOLUTION_BUCKET_TBD = 99
    WORKFLOW_NVLINK5_ERR = 9
    WORKFLOW_XID_45 = 10
    WORKFLOW_XID_48 = 11
    CHECK_MECHANICALS = 12
    WORKFLOW_NVLINK_ERR = 13
    UPDATE_SWFW = 14
    RESTART_VM = 15

  # The below tables should map to the xid error spreadsheet https://docs.google.com/spreadsheets/d/1t6PpsC5TXiNl4JMBuHlFIjmSbjLZ2ik0Sz3DLw8cLmE/edit?gid=121017179#gid=121017179
  # ordering of below columns => xiderrorno,xiderrorname,xiderrorrecommendedaction,FATAL/NONFATAL errors
{{ (.Files.Glob "xiderrorsmapping.csv").AsConfig | indent 2 }}


