//go:build !ignore_autogenerated

//  Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionOverride) DeepCopyInto(out *ActionOverride) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionOverride.
func (in *ActionOverride) DeepCopy() *ActionOverride {
	if in == nil {
		return nil
	}
	out := new(ActionOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BehaviourOverrides) DeepCopyInto(out *BehaviourOverrides) {
	*out = *in
	if in.Quarantine != nil {
		in, out := &in.Quarantine, &out.Quarantine
		*out = new(ActionOverride)
		**out = **in
	}
	if in.Drain != nil {
		in, out := &in.Drain, &out.Drain
		*out = new(ActionOverride)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BehaviourOverrides.
func (in *BehaviourOverrides) DeepCopy() *BehaviourOverrides {
	if in == nil {
		return nil
	}
	out := new(BehaviourOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Entity) DeepCopyInto(out *Entity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Entity.
func (in *Entity) DeepCopy() *Entity {
	if in == nil {
		return nil
	}
	out := new(Entity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthEvent) DeepCopyInto(out *HealthEvent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthEvent.
func (in *HealthEvent) DeepCopy() *HealthEvent {
	if in == nil {
		return nil
	}
	out := new(HealthEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HealthEvent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthEventCondition) DeepCopyInto(out *HealthEventCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthEventCondition.
func (in *HealthEventCondition) DeepCopy() *HealthEventCondition {
	if in == nil {
		return nil
	}
	out := new(HealthEventCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthEventList) DeepCopyInto(out *HealthEventList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HealthEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthEventList.
func (in *HealthEventList) DeepCopy() *HealthEventList {
	if in == nil {
		return nil
	}
	out := new(HealthEventList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HealthEventList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthEventSpec) DeepCopyInto(out *HealthEventSpec) {
	*out = *in
	if in.ErrorCodes != nil {
		in, out := &in.ErrorCodes, &out.ErrorCodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EntitiesImpacted != nil {
		in, out := &in.EntitiesImpacted, &out.EntitiesImpacted
		*out = make([]Entity, len(*in))
		copy(*out, *in)
	}
	in.DetectedAt.DeepCopyInto(&out.DetectedAt)
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(BehaviourOverrides)
		(*in).DeepCopyInto(*out)
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Maintenance != nil {
		in, out := &in.Maintenance, &out.Maintenance
		*out = new(MaintenanceInfo)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthEventSpec.
func (in *HealthEventSpec) DeepCopy() *HealthEventSpec {
	if in == nil {
		return nil
	}
	out := new(HealthEventSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthEventStatus) DeepCopyInto(out *HealthEventStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]HealthEventCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastRemediationTime != nil {
		in, out := &in.LastRemediationTime, &out.LastRemediationTime
		*out = (*in).DeepCopy()
	}
	if in.ResolvedAt != nil {
		in, out := &in.ResolvedAt, &out.ResolvedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthEventStatus.
func (in *HealthEventStatus) DeepCopy() *HealthEventStatus {
	if in == nil {
		return nil
	}
	out := new(HealthEventStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceInfo) DeepCopyInto(out *MaintenanceInfo) {
	*out = *in
	if in.ScheduledStartTime != nil {
		in, out := &in.ScheduledStartTime, &out.ScheduledStartTime
		*out = (*in).DeepCopy()
	}
	if in.ScheduledEndTime != nil {
		in, out := &in.ScheduledEndTime, &out.ScheduledEndTime
		*out = (*in).DeepCopy()
	}
	if in.ActualStartTime != nil {
		in, out := &in.ActualStartTime, &out.ActualStartTime
		*out = (*in).DeepCopy()
	}
	if in.ActualEndTime != nil {
		in, out := &in.ActualEndTime, &out.ActualEndTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceInfo.
func (in *MaintenanceInfo) DeepCopy() *MaintenanceInfo {
	if in == nil {
		return nil
	}
	out := new(MaintenanceInfo)
	in.DeepCopyInto(out)
	return out
}
