# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nvsentinel-system
generatorOptions:
  disableNameSuffixHash: true   # keep the generated ConfigMap name stable
configMapGenerator:
- name: check-existing-workflow-script
  files:
  - scripts/check-existing-workflow.py
  options:
    labels:
      app.kubernetes.io/name: nvsentinel
      app.kubernetes.io/component: workflow
      app.kubernetes.io/part-of: nvsentinel-deployment
- name: update-release-version-script
  files:
  - scripts/update-release-version.py
  options:
    labels:
      app.kubernetes.io/name: nvsentinel
      app.kubernetes.io/component: workflow
      app.kubernetes.io/part-of: nvsentinel-deployment
- name: monitor-release-mr-script
  files:
  - scripts/monitor-release-mr.py
  options:
    labels:
      app.kubernetes.io/name: nvsentinel
      app.kubernetes.io/component: workflow
      app.kubernetes.io/part-of: nvsentinel-deployment
- name: update-sbom-version-script
  files:
  - scripts/update-sbom-version.py
  options:
    labels:
      app.kubernetes.io/name: nvsentinel
      app.kubernetes.io/component: workflow
      app.kubernetes.io/part-of: nvsentinel-deployment
- name: monitor-mr-script
  files:
  - scripts/monitor-mr.py
  options:
    labels:
      app.kubernetes.io/name: nvsentinel
      app.kubernetes.io/component: workflow
      app.kubernetes.io/part-of: nvsentinel-deployment
- name: image-sync-script
  files:
  - scripts/image-sync.py
  options:
    labels:
      app.kubernetes.io/name: nvsentinel
      app.kubernetes.io/component: workflow
      app.kubernetes.io/part-of: nvsentinel-deployment
- name: find-clusters-script
  files:
  - scripts/find-clusters.py
  options:
    labels:
      app.kubernetes.io/name: nvsentinel
      app.kubernetes.io/component: workflow
      app.kubernetes.io/part-of: nvsentinel-deployment
- name: create-mr-script
  files:
  - scripts/create-mr.py
  options:
    labels:
      app.kubernetes.io/name: nvsentinel
      app.kubernetes.io/component: workflow
      app.kubernetes.io/part-of: nvsentinel-deployment
- name: monitor-cluster-mr-script
  files:
  - scripts/monitor-cluster-mr.py
  options:
    labels:
      app.kubernetes.io/name: nvsentinel
      app.kubernetes.io/component: workflow
      app.kubernetes.io/part-of: nvsentinel-deployment
- name: update-version-status-script
  files:
  - scripts/update-version-status.py
  options:
    labels:
      app.kubernetes.io/name: nvsentinel
      app.kubernetes.io/component: workflow
      app.kubernetes.io/part-of: nvsentinel-deployment
resources:
- check-existing-workflow.yaml
- update-release-version.yaml
- monitor-release-mr.yaml
- update-sbom-version.yaml
- monitor-ace-mr.yaml
- monitor-manifest-template-mr.yaml
- update-image-registry.yaml
- monitor-ace-image-sync-mr.yaml
- monitor-nvcr-registry-mr.yaml
- monitor-bcp-registry-mr.yaml
- find-clusters.yaml
- create-mr.yaml
- monitor-cluster-mr.yaml
- update-version-status.yaml