# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: nvsentinel-run-autotest
  namespace: nvsentinel-system
spec:
  serviceAccountName: nvsentinel-workflow-sa
  imagePullSecrets:
  - name: nvidia-ngcuser-pull-secret
  templates:
  - name: run-autotest
    inputs:
      parameters:
      - name: version
      - name: cluster-data
    outputs:
      parameters:
      - name: autotest-result
        valueFrom:
          path: /tmp/autotest-result.json
    
    container:
      image: nvcr.io/nv-ngc-devops/python-gitlab:alpine
      command: ["python3", "-u","/scripts/run-autotest.py"]
      volumeMounts:
      - name: run-autotest-script-volume
        mountPath: /scripts
      env:
      - name: GITLAB_TOKEN
        valueFrom:
          secretKeyRef:
            name: gitlab-credentials
            key: autotest-token
      - name: GITLAB_URL
        valueFrom:
          secretKeyRef:
            name: gitlab-credentials
            key: url
      - name: MR_VERSION
        value: "{{inputs.parameters.version}}"
      - name: CLUSTER_DATA
        value: "{{inputs.parameters.cluster-data}}"
    volumes:
    - name: run-autotest-script-volume
      configMap:
        name: run-autotest-script