nameOverride: ""
fullnameOverride: ""

updateStrategy: RollingUpdate
maxUnavailable: 1

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  runAsUser: 0

  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector:
  nvidia.com/gpu.present: "true"


tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    operator: Exists


affinity: {}

metricsPort: 2112

pollingInterval: 1000
nicExclusionRegexes: "^eth0$" #This is the default nic already being monitored from the daemonset monitor

enableSidecarMonitoringForGKE: true
maxRetryDurationForDownDetectedNICInMilliseconds: 500
retryIntervalForDownDetectedNICInMilliseconds: 100