# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

nameOverride: ""
fullnameOverride: ""

updateStrategy: RollingUpdate
maxUnavailable: 1

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  runAsUser: 0

  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector:
  nvidia.com/gpu.present: "true"


tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    operator: Exists


affinity: {}

metricsPort: 2112

pollingInterval: 1000

nicExclusionRegexesForInjectedContainer: "^eth0$" #This is the default nic already being monitored from the daemonset monitor
nicExclusionRegexes: "^gketmp.*" 
roCEInterfaceRegexes: "^rdma\\\\d+$,^eth\\\\d+$" # Default regex patterns for RoCE interfaces (rdma0, rdma1, eth0, eth1, etc.)

maxRetryDurationForDownDetectedNICInMilliseconds: 500
retryIntervalForDownDetectedNICInMilliseconds: 100
# Custom path for sys/class/net (for testing purposes)
# Leave empty to use default /sys/class/net
sysClassNetPath: ""
sysClassInfinibandPath: ""
