# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import platformconnector_pb2 as platformconnector__pb2


class PlatformConnectorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthEventOccuredV1 = channel.unary_unary(
            "/platformconnector.PlatformConnector/HealthEventOccuredV1",
            request_serializer=platformconnector__pb2.HealthEvents.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class PlatformConnectorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HealthEventOccuredV1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_PlatformConnectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "HealthEventOccuredV1": grpc.unary_unary_rpc_method_handler(
            servicer.HealthEventOccuredV1,
            request_deserializer=platformconnector__pb2.HealthEvents.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "platformconnector.PlatformConnector", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class PlatformConnector(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HealthEventOccuredV1(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/platformconnector.PlatformConnector/HealthEventOccuredV1",
            platformconnector__pb2.HealthEvents.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
