# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
{{ if or (eq .Values.global.clusterType "standalone") (eq .Values.global.clusterType "tenant") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nvswitch-health-monitor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nvswitch-health-monitor.labels" . | nindent 4 }}

data:
  config.ini: |
    PollingIntervalInMilliseconds = 100
    MaxRetriesForHealthyEvent = 20
    RetryDelaySecondsForHealthyEvent = 5

    [sxiderrorrecommendactiontoplatformconnectormapping]
    UNEXPECTED_ERR_REPORT_ISSUE = 5
    RESET_FABRIC = 16
    WORKFLOW_NVLINK_POTENTIALY_FATAL_ERR = 17
    CHECK_FM_CONFIG = 18
    CHECK_THERMALS = 19
    RESET_GPU = 20
    CHECK_LINK_MECHANICAL_CONNECTIONS = 21
    INVESTIGATE_LINK_SI = 22
    IGNORE = 0
    RUN_FIELDDIAG = 6

  # The below tables should map to the xid error spreadsheet https://docs.google.com/spreadsheets/d/1t6PpsC5TXiNl4JMBuHlFIjmSbjLZ2ik0Sz3DLw8cLmE/edit?gid=121017179#gid=121017179
  # ordering of below columns => sxiderrorno,sxiderrorname,sxiderrorrecommendedaction,FATAL/NONFATAL errors
{{ (.Files.Glob "sxiderrorsmapping.csv").AsConfig | indent 2 }}
{{ end }}