apiVersion: v2
name: nvsentinel
description: Helm chart for NVSentinel
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: "example-health-monitor"
  - name: "gpu-health-monitor"
  - name: "nic-health-monitor"
  - name: "nvswitch-health-monitor"
