apiVersion: v2
name: nvsentinel
description: Helm chart for NVSentinel
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: gpu-health-monitor
    version: "0.1.0"
  - name: nic-health-monitor
    version: "0.1.0"
  - name: nvswitch-health-monitor
    version: "0.1.0"
  - name: shoreline-agent
    version: v27.2.0
    repository: https://helm.ngc.nvidia.com/nv-ngc-devops
    condition: shoreline-agent.global.enabled
