global:
  image:
    tag: "main"

  gpuHealthMonitorAdditionalHostVolumes:
    - name: vulkan-icd-mount
      hostPath:
        path: /home/kubernetes/bin/nvidia/vulkan/icd.d
        type: Directory
    - name: nvidia-install-dir-host
      hostPath:
        path: /home/kubernetes/bin/nvidia
        type: Directory

  gpuHealthMonitorAdditionalVolumeMounts:
    - mountPath: /usr/local/nvidia
      name: nvidia-install-dir-host
      readOnly: true
    - mountPath: /etc/vulkan/icd.d
      name: vulkan-icd-mount
      readOnly: true

platformConnector:
  image:
    repository: nvcr.io/nv-ngc-devops/nvsentinel/platform-connectors
    pullPolicy: IfNotPresent

  resources: 
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 512Mi

  securityContext:
    runAsUser: 0
    capabilities:
      drop:
      - ALL

  kubectlImage: "nvcr.io/nv-ngc-devops/kubectl:1.28.5"

  podSecurityContext: {}

  updateStrategy: RollingUpdate
  maxUnavailable: 1

imagePullSecrets: 
  - name: nvidia-ngcuser-pull-secret

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}

socketPath: "/var/run/nvsentinel.sock"

