# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

global:
  image:
    tag: "main"

  dcgm:
    dcgmK8sServiceEnabled: true
    service:
      endpoint: "nvidia-dcgm.gpu-operator.svc"
      port: 5555

  dryRun: false

  gpuHealthMonitor:
    enabled: true

    image:
      repository: nvcr.io/nv-ngc-devops/nvsentinel-gpu-health-monitor
      pullPolicy: IfNotPresent
    
    useHostNetworking: false
    
    busybox:
      image:
        repository: nvcr.io/nv-ngc-devops/busybox
        tag: "1.37.0"
        pullPolicy: IfNotPresent


  nicHealthMonitor:
    enabled: true
    nicExclusionRegexesForInjectedContainer: "^eth0$" #This is the default nic already being monitored from the daemonset monitor
    nicExclusionRegexes: "^gketmp.*"
    monitorNetworkType: "all"
    roCEInterfaceRegexes: "^rdma\\\\d+$,^eth\\\\d+$"  # Default regex patterns for RoCE interfaces
    image:
      repository: nvcr.io/nv-ngc-devops/nvsentinel-nic-health-monitor
      pullPolicy: IfNotPresent


  healthEventsAnalyzer:
    enabled: false
    image:
      repository: nvcr.io/nv-ngc-devops/nvsentinel-health-events-analyzer
      pullPolicy: IfNotPresent

  faultQuarantineModule:
    enabled: false

    image:
      repository: nvcr.io/nv-ngc-devops/nvsentinel-fault-quarantine-module
      pullPolicy: IfNotPresent

  nodeDrainerModule:
    enabled: false

    image:
      repository: nvcr.io/nv-ngc-devops/nvsentinel-node-drainer-module
      pullPolicy: IfNotPresent

  faultRemediationModule:
    enabled: false

    image:
      repository: nvcr.io/nv-ngc-devops/nvsentinel-fault-remediation-module
      pullPolicy: IfNotPresent

  nvSwitchHealthMonitor:
    enabled: true

    image:
      repository: nvcr.io/nv-ngc-devops/nvsentinel-nvswitch-health-monitor
      pullPolicy: IfNotPresent

  dcaHealthMonitor:
    enabled: false
    image:
      repository: nvcr.io/nv-ngc-devops/nvsentinel-nvs_healthcheck-dev
      pullPolicy: IfNotPresent
  
  cspHealthMonitor:
    enabled: false

    image:
      repository: nvcr.io/nv-ngc-devops/nvsentinel-csp-health-monitor
      pullPolicy: IfNotPresent

  syslogHealthMonitor:
    enabled: false

    image:
      repository: nvcr.io/nv-ngc-devops/nvsentinel-syslog-health-monitor
      pullPolicy: IfNotPresent

  imagePullSecrets:
    - name: nvidia-ngcuser-pull-secret

  enableSidecarNICMonitoringForGKE: false

  mongodbStore:
    images:
      mongosh:
        repository: nvcr.io/nv-ngc-devops/rtsp-mongosh
        tag: "2.5.2"
        pullPolicy: IfNotPresent

  clusterType: standalone # standalone|mgmt|tenant

platformConnector:
  image:
    repository: nvcr.io/nv-ngc-devops/nvsentinel-platform-connectors
    pullPolicy: IfNotPresent

  resources: 
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 512Mi

  securityContext:
    runAsUser: 0
    capabilities:
      drop:
      - ALL
      
  metricsPort: 2112

  mongodbStore:
    enabled: false
    clientCertMountPath: "/etc/ssl/mongo-client"

  podSecurityContext: {}

  updateStrategy: RollingUpdate
  maxUnavailable: 1

  k8sConnector:
    enabled: true
    qps: 5.0
    burst: 10
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}

socketPath: "/var/run/nvsentinel.sock"
nodeHealthEventsSocketPath: "/var/run/nodeHealthEvents.sock"