# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
{{ if or (eq .Values.global.clusterType "standalone") (eq .Values.global.clusterType "mgmt") }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-mongodb-database
  namespace: {{ .Release.Namespace }}

spec:
  activeDeadlineSeconds: 600
  template:
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: mongo-client
        image: "{{ .Values.global.mongodbStore.images.mongosh.repository }}:{{ .Values.global.mongodbStore.images.mongosh.tag }}"
        imagePullPolicy: {{ .Values.global.mongodbStore.images.mongosh.pullPolicy }}
        command:
          - sh
          - -c
          - |
            set -e

            echo "=============================="
            echo "Starting mongodb client job..."
            echo "=============================="

            echo "MONGODB_URI: $MONGODB_URI"
            echo "MONGODB_APPLICATION_USER_DN: $MONGODB_APPLICATION_USER_DN"
            echo "MONGODB_DATABASE_NAME: $MONGODB_DATABASE_NAME"
            echo "MONGODB_COLLECTION_NAME: $MONGODB_COLLECTION_NAME"
            echo "MONGODB_TOKEN_COLLECTION_NAME: $MONGODB_TOKEN_COLLECTION_NAME"

            cat /certs/tls.crt /certs/tls.key > /tmp/tls.pem

            echo "=============================="
            echo "Connecting to mongodb and creating X.509 user..."
            echo "=============================="

            until mongosh "$MONGODB_URI" \
              --authenticationMechanism SCRAM-SHA-256 \
              --username root --password "$MONGODB_ROOT_PASSWORD" --authenticationDatabase admin \
              --tls \
              --tlsCAFile /certs/ca.crt \
              --tlsCertificateKeyFile /tmp/tls.pem \
              --eval "
                db = db.getSiblingDB('$MONGODB_DATABASE_NAME');
                db.createCollection('$MONGODB_COLLECTION_NAME');
                db.createCollection('$MONGODB_TOKEN_COLLECTION_NAME');
                db.$MONGODB_COLLECTION_NAME.createIndex(
                  { 'createdAt': 1 },                 
                  { expireAfterSeconds: $MONGODB_COLLECTION_EXPIRY_SECONDS }      
                );
                db.createCollection('$MONGODB_MAINTENANCE_EVENT_COLLECTION_NAME');
                db.$MONGODB_MAINTENANCE_EVENT_COLLECTION_NAME.createIndex(
                  { 'actualEndTime': 1 },    
                  { expireAfterSeconds: $MONGODB_COLLECTION_EXPIRY_SECONDS }                  
                );
                db.$MONGODB_MAINTENANCE_EVENT_COLLECTION_NAME.createIndex(
                  { 'scheduledStartTime': 1 },
                );
                db.$MONGODB_MAINTENANCE_EVENT_COLLECTION_NAME.createIndex(
                  { 'cspStatus': 1 },
                );
                db.getSiblingDB('\$external').runCommand({
                  createUser: '$MONGODB_APPLICATION_USER_DN',
                  roles: [{ role: 'readWrite', db: '$MONGODB_DATABASE_NAME' }]
                });"
            do
              echo "Waiting for mongodb to be ready...";
              sleep 5;
            done

            echo "=============================="
            echo "mongodb user creation completed."
            echo "=============================="
        env:
          - name: MONGODB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-mongodb
                key: mongodb-root-password
          - name: MONGODB_APPLICATION_USER_DN
            value: "CN=mongo-user-client,OU=DGXC,O=Nvidia,L=SantaClara,ST=California,C=US"
        envFrom:
          - configMapRef:
              name: mongodb-config
        volumeMounts:
          - name: mongo-certificates
            mountPath: /certs
            readOnly: true
      volumes:
        - name: mongo-certificates
          secret:
            secretName: mongo-app-client-cert-secret
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
              - key: ca.crt
                path: ca.crt
      {{- if not (eq $.Values.global.clusterType "mgmt") }}
      {{- with .Values.mongodb.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      restartPolicy: OnFailure
{{ end }}
