// Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";
package platformconnector;

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";

option go_package = "gitlab-master.nvidia.com/dgxcloud/mk8s/k8s-addons/nvsentinel/platform-connectors";

service PlatformConnector {
  rpc HealthEventOccuredV1(HealthEvents) returns (google.protobuf.Empty) {}
}

message HealthEvents {
  uint32 version = 1;
  repeated HealthEvent events = 2;
}

enum RecommenedAction {
  NONE = 0;
  NODE_REBOOT = 1;
  COMPONENT_RESET = 2;
  COMPONENT_REPLACEMENT = 3;
  APPLICATION_RESTART = 4;
  REPORT_ISSUE = 5;
  RUN_FIELDDIAG = 6;
  WORKFLOW_XID_13_31 = 7;
  WORKFLOW_ECC_DBE_SRAM = 8;
  WORKFLOW_NVLINK5_ERR = 9;
  WORKFLOW_XID_45 = 10;
  WORKFLOW_XID_48 = 11;
  CHECK_MECHANICALS = 12;
  WORKFLOW_NVLINK_ERR = 13;
  UPDATE_SWFW = 14;
  RESTART_VM = 15;
  RESET_FABRIC = 16;
  WORKFLOW_NVLINK_POTENTIALY_FATAL_ERR = 17;
  CHECK_FM_CONFIG = 18;
  CHECK_THERMALS = 19;
  RESET_GPU = 20;
  CHECK_LINK_MECHANICAL_CONNECTIONS = 21;
  INVESTIGATE_LINK_SI = 22;
  CHECK_UVM = 23;
	RESTART_BM = 24;

  UNKNOWN = 99;
}

message Entity {
  string entityType = 1;
  string entityValue = 2;
}

message HealthEvent {
  uint32 version = 1;

  string agent = 2;
  string componentClass = 3;

  string checkName = 4;
  bool isFatal = 5;
  bool isHealthy = 6;
  string message = 7;
  RecommenedAction recommendedAction = 8;
  repeated string errorCode = 9;
  repeated Entity entitiesImpacted = 10;

  map<string, string> metadata = 11;
  google.protobuf.Timestamp generatedTimestamp = 12;
  string nodeName = 13;
  BehaviourOverrides quarantineOverrides = 14;
  BehaviourOverrides drainOverrides = 15;
}

message BehaviourOverrides {
  bool force = 1;
  bool skip = 2;
}
